/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ConnState.proto */

#ifndef PROTOBUF_C_ConnState_2eproto__INCLUDED
#define PROTOBUF_C_ConnState_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "Inaddr.pb-c.h"

typedef struct _ConnState ConnState;


/* --- enums --- */


/* --- messages --- */

struct  _ConnState
{
  ProtobufCMessage base;
  size_t n_ether_dst;
  uint32_t *ether_dst;
  size_t n_ether_src;
  uint32_t *ether_src;
  Inaddr *s_ip;
  Inaddr *d_ip;
  uint32_t s_port;
  uint32_t d_port;
  protobuf_c_boolean has_cxid;
  uint64_t cxid;
  protobuf_c_boolean has_hash;
  uint32_t hash;
};
#define CONN_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conn_state__descriptor) \
    , 0,NULL, 0,NULL, NULL, NULL, 0, 0, 0, 0, 0, 0 }


/* ConnState methods */
void   conn_state__init
                     (ConnState         *message);
size_t conn_state__get_packed_size
                     (const ConnState   *message);
size_t conn_state__pack
                     (const ConnState   *message,
                      uint8_t             *out);
size_t conn_state__pack_to_buffer
                     (const ConnState   *message,
                      ProtobufCBuffer     *buffer);
ConnState *
       conn_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conn_state__free_unpacked
                     (ConnState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ConnState_Closure)
                 (const ConnState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor conn_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ConnState_2eproto__INCLUDED */
