/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ConnState.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ConnState.pb-c.h"
void   conn_state__init
                     (ConnState         *message)
{
  static const ConnState init_value = CONN_STATE__INIT;
  *message = init_value;
}
size_t conn_state__get_packed_size
                     (const ConnState *message)
{
  assert(message->base.descriptor == &conn_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conn_state__pack
                     (const ConnState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conn_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conn_state__pack_to_buffer
                     (const ConnState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conn_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnState *
       conn_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnState *)
     protobuf_c_message_unpack (&conn_state__descriptor,
                                allocator, len, data);
}
void   conn_state__free_unpacked
                     (ConnState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conn_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor conn_state__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ConnState, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conn_state__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange conn_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor conn_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnState",
  "ConnState",
  "ConnState",
  "",
  sizeof(ConnState),
  1,
  conn_state__field_descriptors,
  conn_state__field_indices_by_name,
  1,  conn_state__number_ranges,
  (ProtobufCMessageInit) conn_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
