/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: connGetPerflowAckMsg.proto */

#ifndef PROTOBUF_C_connGetPerflowAckMsg_2eproto__INCLUDED
#define PROTOBUF_C_connGetPerflowAckMsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ConnGetPerflowAckMsg ConnGetPerflowAckMsg;


/* --- enums --- */


/* --- messages --- */

struct  _ConnGetPerflowAckMsg
{
  ProtobufCMessage base;
  uint32_t count;
};
#define CONN_GET_PERFLOW_ACK_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conn_get_perflow_ack_msg__descriptor) \
    , 0 }


/* ConnGetPerflowAckMsg methods */
void   conn_get_perflow_ack_msg__init
                     (ConnGetPerflowAckMsg         *message);
size_t conn_get_perflow_ack_msg__get_packed_size
                     (const ConnGetPerflowAckMsg   *message);
size_t conn_get_perflow_ack_msg__pack
                     (const ConnGetPerflowAckMsg   *message,
                      uint8_t             *out);
size_t conn_get_perflow_ack_msg__pack_to_buffer
                     (const ConnGetPerflowAckMsg   *message,
                      ProtobufCBuffer     *buffer);
ConnGetPerflowAckMsg *
       conn_get_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conn_get_perflow_ack_msg__free_unpacked
                     (ConnGetPerflowAckMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ConnGetPerflowAckMsg_Closure)
                 (const ConnGetPerflowAckMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor conn_get_perflow_ack_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_connGetPerflowAckMsg_2eproto__INCLUDED */
