/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Inaddr.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Inaddr.pb-c.h"
void   inaddr__init
                     (Inaddr         *message)
{
  static const Inaddr init_value = INADDR__INIT;
  *message = init_value;
}
size_t inaddr__get_packed_size
                     (const Inaddr *message)
{
  assert(message->base.descriptor == &inaddr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t inaddr__pack
                     (const Inaddr *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &inaddr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t inaddr__pack_to_buffer
                     (const Inaddr *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &inaddr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Inaddr *
       inaddr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Inaddr *)
     protobuf_c_message_unpack (&inaddr__descriptor,
                                allocator, len, data);
}
void   inaddr__free_unpacked
                     (Inaddr *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &inaddr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor inaddr__field_descriptors[1] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Inaddr, n_address),
    offsetof(Inaddr, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned inaddr__field_indices_by_name[] = {
  0,   /* field[0] = address */
};
static const ProtobufCIntRange inaddr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor inaddr__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Inaddr",
  "Inaddr",
  "Inaddr",
  "",
  sizeof(Inaddr),
  1,
  inaddr__field_descriptors,
  inaddr__field_indices_by_name,
  1,  inaddr__number_ranges,
  (ProtobufCMessageInit) inaddr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
