/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Inaddr.proto */

#ifndef PROTOBUF_C_Inaddr_2eproto__INCLUDED
#define PROTOBUF_C_Inaddr_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Inaddr Inaddr;


/* --- enums --- */


/* --- messages --- */

struct  _Inaddr
{
  ProtobufCMessage base;
  size_t n_address;
  uint32_t *address;
};
#define INADDR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&inaddr__descriptor) \
    , 0,NULL }


/* Inaddr methods */
void   inaddr__init
                     (Inaddr         *message);
size_t inaddr__get_packed_size
                     (const Inaddr   *message);
size_t inaddr__pack
                     (const Inaddr   *message,
                      uint8_t             *out);
size_t inaddr__pack_to_buffer
                     (const Inaddr   *message,
                      ProtobufCBuffer     *buffer);
Inaddr *
       inaddr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   inaddr__free_unpacked
                     (Inaddr *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Inaddr_Closure)
                 (const Inaddr *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor inaddr__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Inaddr_2eproto__INCLUDED */
