/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: syn.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "syn.pb-c.h"
void   syn__init
                     (Syn         *message)
{
  static const Syn init_value = SYN__INIT;
  *message = init_value;
}
size_t syn__get_packed_size
                     (const Syn *message)
{
  assert(message->base.descriptor == &syn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t syn__pack
                     (const Syn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &syn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t syn__pack_to_buffer
                     (const Syn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &syn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Syn *
       syn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Syn *)
     protobuf_c_message_unpack (&syn__descriptor,
                                allocator, len, data);
}
void   syn__free_unpacked
                     (Syn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &syn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor syn__field_descriptors[2] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Syn, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Syn, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned syn__field_indices_by_name[] = {
  0,   /* field[0] = host */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange syn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor syn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Syn",
  "Syn",
  "Syn",
  "",
  sizeof(Syn),
  2,
  syn__field_descriptors,
  syn__field_indices_by_name,
  1,  syn__number_ranges,
  (ProtobufCMessageInit) syn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
