/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cinformation.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cinformation.pb-c.h"
void   cinformation__init
                     (Cinformation         *message)
{
  static const Cinformation init_value = CINFORMATION__INIT;
  *message = init_value;
}
size_t cinformation__get_packed_size
                     (const Cinformation *message)
{
  assert(message->base.descriptor == &cinformation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cinformation__pack
                     (const Cinformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cinformation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cinformation__pack_to_buffer
                     (const Cinformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cinformation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cinformation *
       cinformation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cinformation *)
     protobuf_c_message_unpack (&cinformation__descriptor,
                                allocator, len, data);
}
void   cinformation__free_unpacked
                     (Cinformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cinformation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cinformation__field_descriptors[4] =
{
  {
    "personnum",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Cinformation, personnum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cinformation, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "student",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Cinformation, student),
    &student__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cinfo",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Cinformation, cinfo),
    &cinformation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cinformation__field_indices_by_name[] = {
  3,   /* field[3] = cinfo */
  1,   /* field[1] = content */
  0,   /* field[0] = personnum */
  2,   /* field[2] = student */
};
static const ProtobufCIntRange cinformation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cinformation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Cinformation",
  "Cinformation",
  "Cinformation",
  "",
  sizeof(Cinformation),
  4,
  cinformation__field_descriptors,
  cinformation__field_indices_by_name,
  1,  cinformation__number_ranges,
  (ProtobufCMessageInit) cinformation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
