/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bstring.proto */

#ifndef PROTOBUF_C_bstring_2eproto__INCLUDED
#define PROTOBUF_C_bstring_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Bstring Bstring;


/* --- enums --- */


/* --- messages --- */

struct  _Bstring
{
  ProtobufCMessage base;
  uint32_t mlen;
  uint32_t slen;
  char *data;
};
#define BSTRING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bstring__descriptor) \
    , 0, 0, NULL }


/* Bstring methods */
void   bstring__init
                     (Bstring         *message);
size_t bstring__get_packed_size
                     (const Bstring   *message);
size_t bstring__pack
                     (const Bstring   *message,
                      uint8_t             *out);
size_t bstring__pack_to_buffer
                     (const Bstring   *message,
                      ProtobufCBuffer     *buffer);
Bstring *
       bstring__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bstring__free_unpacked
                     (Bstring *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Bstring_Closure)
                 (const Bstring *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor bstring__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_bstring_2eproto__INCLUDED */
