/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: myActionMessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "myActionMessage.pb-c.h"
void   my_action_message__init
                     (MyActionMessage         *message)
{
  static const MyActionMessage init_value = MY_ACTION_MESSAGE__INIT;
  *message = init_value;
}
size_t my_action_message__get_packed_size
                     (const MyActionMessage *message)
{
  assert(message->base.descriptor == &my_action_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t my_action_message__pack
                     (const MyActionMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &my_action_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t my_action_message__pack_to_buffer
                     (const MyActionMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &my_action_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MyActionMessage *
       my_action_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MyActionMessage *)
     protobuf_c_message_unpack (&my_action_message__descriptor,
                                allocator, len, data);
}
void   my_action_message__free_unpacked
                     (MyActionMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &my_action_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_syn__init
                     (ActionSyn         *message)
{
  static const ActionSyn init_value = ACTION_SYN__INIT;
  *message = init_value;
}
size_t action_syn__get_packed_size
                     (const ActionSyn *message)
{
  assert(message->base.descriptor == &action_syn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_syn__pack
                     (const ActionSyn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_syn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_syn__pack_to_buffer
                     (const ActionSyn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_syn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionSyn *
       action_syn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionSyn *)
     protobuf_c_message_unpack (&action_syn__descriptor,
                                allocator, len, data);
}
void   action_syn__free_unpacked
                     (ActionSyn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_syn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_state__init
                     (ActionState         *message)
{
  static const ActionState init_value = ACTION_STATE__INIT;
  *message = init_value;
}
size_t action_state__get_packed_size
                     (const ActionState *message)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_state__pack
                     (const ActionState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_state__pack_to_buffer
                     (const ActionState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionState *
       action_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionState *)
     protobuf_c_message_unpack (&action_state__descriptor,
                                allocator, len, data);
}
void   action_state__free_unpacked
                     (ActionState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   share_state__init
                     (ShareState         *message)
{
  static const ShareState init_value = SHARE_STATE__INIT;
  *message = init_value;
}
size_t share_state__get_packed_size
                     (const ShareState *message)
{
  assert(message->base.descriptor == &share_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t share_state__pack
                     (const ShareState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &share_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t share_state__pack_to_buffer
                     (const ShareState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &share_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShareState *
       share_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShareState *)
     protobuf_c_message_unpack (&share_state__descriptor,
                                allocator, len, data);
}
void   share_state__free_unpacked
                     (ShareState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &share_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_perflow_msg__init
                     (ActionGetPerflowMsg         *message)
{
  static const ActionGetPerflowMsg init_value = ACTION_GET_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_get_perflow_msg__get_packed_size
                     (const ActionGetPerflowMsg *message)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_perflow_msg__pack
                     (const ActionGetPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_perflow_msg__pack_to_buffer
                     (const ActionGetPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetPerflowMsg *
       action_get_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetPerflowMsg *)
     protobuf_c_message_unpack (&action_get_perflow_msg__descriptor,
                                allocator, len, data);
}
void   action_get_perflow_msg__free_unpacked
                     (ActionGetPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_perflow_ack_msg__init
                     (ActionGetPerflowAckMsg         *message)
{
  static const ActionGetPerflowAckMsg init_value = ACTION_GET_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_get_perflow_ack_msg__get_packed_size
                     (const ActionGetPerflowAckMsg *message)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_perflow_ack_msg__pack
                     (const ActionGetPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_perflow_ack_msg__pack_to_buffer
                     (const ActionGetPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetPerflowAckMsg *
       action_get_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetPerflowAckMsg *)
     protobuf_c_message_unpack (&action_get_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_get_perflow_ack_msg__free_unpacked
                     (ActionGetPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_perflow_msg__init
                     (ActionPutPerflowMsg         *message)
{
  static const ActionPutPerflowMsg init_value = ACTION_PUT_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_put_perflow_msg__get_packed_size
                     (const ActionPutPerflowMsg *message)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_perflow_msg__pack
                     (const ActionPutPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_perflow_msg__pack_to_buffer
                     (const ActionPutPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutPerflowMsg *
       action_put_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutPerflowMsg *)
     protobuf_c_message_unpack (&action_put_perflow_msg__descriptor,
                                allocator, len, data);
}
void   action_put_perflow_msg__free_unpacked
                     (ActionPutPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_perflow_ack_msg__init
                     (ActionPutPerflowAckMsg         *message)
{
  static const ActionPutPerflowAckMsg init_value = ACTION_PUT_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_put_perflow_ack_msg__get_packed_size
                     (const ActionPutPerflowAckMsg *message)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_perflow_ack_msg__pack
                     (const ActionPutPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_perflow_ack_msg__pack_to_buffer
                     (const ActionPutPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutPerflowAckMsg *
       action_put_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutPerflowAckMsg *)
     protobuf_c_message_unpack (&action_put_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_put_perflow_ack_msg__free_unpacked
                     (ActionPutPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_multiflow_msg__init
                     (ActionGetMultiflowMsg         *message)
{
  static const ActionGetMultiflowMsg init_value = ACTION_GET_MULTIFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_get_multiflow_msg__get_packed_size
                     (const ActionGetMultiflowMsg *message)
{
  assert(message->base.descriptor == &action_get_multiflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_multiflow_msg__pack
                     (const ActionGetMultiflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_multiflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_multiflow_msg__pack_to_buffer
                     (const ActionGetMultiflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_multiflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetMultiflowMsg *
       action_get_multiflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetMultiflowMsg *)
     protobuf_c_message_unpack (&action_get_multiflow_msg__descriptor,
                                allocator, len, data);
}
void   action_get_multiflow_msg__free_unpacked
                     (ActionGetMultiflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_multiflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_multiflow_ack_msg__init
                     (ActionGetMultiflowAckMsg         *message)
{
  static const ActionGetMultiflowAckMsg init_value = ACTION_GET_MULTIFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_get_multiflow_ack_msg__get_packed_size
                     (const ActionGetMultiflowAckMsg *message)
{
  assert(message->base.descriptor == &action_get_multiflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_multiflow_ack_msg__pack
                     (const ActionGetMultiflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_multiflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_multiflow_ack_msg__pack_to_buffer
                     (const ActionGetMultiflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_multiflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetMultiflowAckMsg *
       action_get_multiflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetMultiflowAckMsg *)
     protobuf_c_message_unpack (&action_get_multiflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_get_multiflow_ack_msg__free_unpacked
                     (ActionGetMultiflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_multiflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_multi_state__init
                     (ActionMultiState         *message)
{
  static const ActionMultiState init_value = ACTION_MULTI_STATE__INIT;
  *message = init_value;
}
size_t action_multi_state__get_packed_size
                     (const ActionMultiState *message)
{
  assert(message->base.descriptor == &action_multi_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_multi_state__pack
                     (const ActionMultiState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_multi_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_multi_state__pack_to_buffer
                     (const ActionMultiState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_multi_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionMultiState *
       action_multi_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionMultiState *)
     protobuf_c_message_unpack (&action_multi_state__descriptor,
                                allocator, len, data);
}
void   action_multi_state__free_unpacked
                     (ActionMultiState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_multi_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_multiflow_msg__init
                     (ActionPutMultiflowMsg         *message)
{
  static const ActionPutMultiflowMsg init_value = ACTION_PUT_MULTIFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_put_multiflow_msg__get_packed_size
                     (const ActionPutMultiflowMsg *message)
{
  assert(message->base.descriptor == &action_put_multiflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_multiflow_msg__pack
                     (const ActionPutMultiflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_multiflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_multiflow_msg__pack_to_buffer
                     (const ActionPutMultiflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_multiflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutMultiflowMsg *
       action_put_multiflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutMultiflowMsg *)
     protobuf_c_message_unpack (&action_put_multiflow_msg__descriptor,
                                allocator, len, data);
}
void   action_put_multiflow_msg__free_unpacked
                     (ActionPutMultiflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_multiflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_multiflow_ack_msg__init
                     (ActionPutMultiflowAckMsg         *message)
{
  static const ActionPutMultiflowAckMsg init_value = ACTION_PUT_MULTIFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_put_multiflow_ack_msg__get_packed_size
                     (const ActionPutMultiflowAckMsg *message)
{
  assert(message->base.descriptor == &action_put_multiflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_multiflow_ack_msg__pack
                     (const ActionPutMultiflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_multiflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_multiflow_ack_msg__pack_to_buffer
                     (const ActionPutMultiflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_multiflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutMultiflowAckMsg *
       action_put_multiflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutMultiflowAckMsg *)
     protobuf_c_message_unpack (&action_put_multiflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_put_multiflow_ack_msg__free_unpacked
                     (ActionPutMultiflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_multiflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_allflow_msg__init
                     (ActionGetAllflowMsg         *message)
{
  static const ActionGetAllflowMsg init_value = ACTION_GET_ALLFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_get_allflow_msg__get_packed_size
                     (const ActionGetAllflowMsg *message)
{
  assert(message->base.descriptor == &action_get_allflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_allflow_msg__pack
                     (const ActionGetAllflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_allflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_allflow_msg__pack_to_buffer
                     (const ActionGetAllflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_allflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetAllflowMsg *
       action_get_allflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetAllflowMsg *)
     protobuf_c_message_unpack (&action_get_allflow_msg__descriptor,
                                allocator, len, data);
}
void   action_get_allflow_msg__free_unpacked
                     (ActionGetAllflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_allflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_allflow_ack_msg__init
                     (ActionGetAllflowAckMsg         *message)
{
  static const ActionGetAllflowAckMsg init_value = ACTION_GET_ALLFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_get_allflow_ack_msg__get_packed_size
                     (const ActionGetAllflowAckMsg *message)
{
  assert(message->base.descriptor == &action_get_allflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_allflow_ack_msg__pack
                     (const ActionGetAllflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_allflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_allflow_ack_msg__pack_to_buffer
                     (const ActionGetAllflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_allflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetAllflowAckMsg *
       action_get_allflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetAllflowAckMsg *)
     protobuf_c_message_unpack (&action_get_allflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_get_allflow_ack_msg__free_unpacked
                     (ActionGetAllflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_allflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_all_state__init
                     (ActionAllState         *message)
{
  static const ActionAllState init_value = ACTION_ALL_STATE__INIT;
  *message = init_value;
}
size_t action_all_state__get_packed_size
                     (const ActionAllState *message)
{
  assert(message->base.descriptor == &action_all_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_all_state__pack
                     (const ActionAllState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_all_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_all_state__pack_to_buffer
                     (const ActionAllState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_all_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionAllState *
       action_all_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionAllState *)
     protobuf_c_message_unpack (&action_all_state__descriptor,
                                allocator, len, data);
}
void   action_all_state__free_unpacked
                     (ActionAllState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_all_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_allflow_msg__init
                     (ActionPutAllflowMsg         *message)
{
  static const ActionPutAllflowMsg init_value = ACTION_PUT_ALLFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_put_allflow_msg__get_packed_size
                     (const ActionPutAllflowMsg *message)
{
  assert(message->base.descriptor == &action_put_allflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_allflow_msg__pack
                     (const ActionPutAllflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_allflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_allflow_msg__pack_to_buffer
                     (const ActionPutAllflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_allflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutAllflowMsg *
       action_put_allflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutAllflowMsg *)
     protobuf_c_message_unpack (&action_put_allflow_msg__descriptor,
                                allocator, len, data);
}
void   action_put_allflow_msg__free_unpacked
                     (ActionPutAllflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_allflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_allflow_ack_msg__init
                     (ActionPutAllflowAckMsg         *message)
{
  static const ActionPutAllflowAckMsg init_value = ACTION_PUT_ALLFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_put_allflow_ack_msg__get_packed_size
                     (const ActionPutAllflowAckMsg *message)
{
  assert(message->base.descriptor == &action_put_allflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_allflow_ack_msg__pack
                     (const ActionPutAllflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_allflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_allflow_ack_msg__pack_to_buffer
                     (const ActionPutAllflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_allflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutAllflowAckMsg *
       action_put_allflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutAllflowAckMsg *)
     protobuf_c_message_unpack (&action_put_allflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_put_allflow_ack_msg__free_unpacked
                     (ActionPutAllflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_allflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   asset__init
                     (Asset         *message)
{
  static const Asset init_value = ASSET__INIT;
  *message = init_value;
}
size_t asset__get_packed_size
                     (const Asset *message)
{
  assert(message->base.descriptor == &asset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t asset__pack
                     (const Asset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &asset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t asset__pack_to_buffer
                     (const Asset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &asset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Asset *
       asset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Asset *)
     protobuf_c_message_unpack (&asset__descriptor,
                                allocator, len, data);
}
void   asset__free_unpacked
                     (Asset *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &asset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   serv_asset__init
                     (ServAsset         *message)
{
  static const ServAsset init_value = SERV_ASSET__INIT;
  *message = init_value;
}
size_t serv_asset__get_packed_size
                     (const ServAsset *message)
{
  assert(message->base.descriptor == &serv_asset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t serv_asset__pack
                     (const ServAsset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &serv_asset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t serv_asset__pack_to_buffer
                     (const ServAsset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &serv_asset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServAsset *
       serv_asset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServAsset *)
     protobuf_c_message_unpack (&serv_asset__descriptor,
                                allocator, len, data);
}
void   serv_asset__free_unpacked
                     (ServAsset *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &serv_asset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   os_asset__init
                     (OsAsset         *message)
{
  static const OsAsset init_value = OS_ASSET__INIT;
  *message = init_value;
}
size_t os_asset__get_packed_size
                     (const OsAsset *message)
{
  assert(message->base.descriptor == &os_asset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t os_asset__pack
                     (const OsAsset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &os_asset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t os_asset__pack_to_buffer
                     (const OsAsset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &os_asset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OsAsset *
       os_asset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OsAsset *)
     protobuf_c_message_unpack (&os_asset__descriptor,
                                allocator, len, data);
}
void   os_asset__free_unpacked
                     (OsAsset *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &os_asset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bstring__init
                     (Bstring         *message)
{
  static const Bstring init_value = BSTRING__INIT;
  *message = init_value;
}
size_t bstring__get_packed_size
                     (const Bstring *message)
{
  assert(message->base.descriptor == &bstring__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bstring__pack
                     (const Bstring *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bstring__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bstring__pack_to_buffer
                     (const Bstring *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bstring__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bstring *
       bstring__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bstring *)
     protobuf_c_message_unpack (&bstring__descriptor,
                                allocator, len, data);
}
void   bstring__free_unpacked
                     (Bstring *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bstring__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue my_action_message__data_type__enum_values_by_number[17] =
{
  { "SynType", "MY_ACTION_MESSAGE__DATA_TYPE__SynType", 1 },
  { "ActionGetPerflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetPerflowMsgType", 2 },
  { "ActionGetPerflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetPerflowAckMsgType", 3 },
  { "ActionStateType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionStateType", 4 },
  { "ActionPutPerflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutPerflowMsgType", 5 },
  { "ActionPutPerflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutPerflowAckMsgType", 6 },
  { "ActionGetMultiflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetMultiflowMsgType", 8 },
  { "ActionGetMultiflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetMultiflowAckMsgType", 9 },
  { "ActionMultiStateType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionMultiStateType", 10 },
  { "ActionPutMultiflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutMultiflowMsgType", 11 },
  { "ActionPutMultiflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutMultiflowAckMsgType", 12 },
  { "ActionGetAllflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetAllflowMsgType", 13 },
  { "ActionGetAllflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetAllflowAckMsgType", 14 },
  { "ActionAllStateType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionAllStateType", 15 },
  { "ActionPutAllflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutAllflowMsgType", 16 },
  { "ActionPutAllflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutAllflowAckMsgType", 17 },
  { "ActionShareStateType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionShareStateType", 18 },
};
static const ProtobufCIntRange my_action_message__data_type__value_ranges[] = {
{1, 0},{8, 6},{0, 17}
};
static const ProtobufCEnumValueIndex my_action_message__data_type__enum_values_by_name[17] =
{
  { "ActionAllStateType", 13 },
  { "ActionGetAllflowAckMsgType", 12 },
  { "ActionGetAllflowMsgType", 11 },
  { "ActionGetMultiflowAckMsgType", 7 },
  { "ActionGetMultiflowMsgType", 6 },
  { "ActionGetPerflowAckMsgType", 2 },
  { "ActionGetPerflowMsgType", 1 },
  { "ActionMultiStateType", 8 },
  { "ActionPutAllflowAckMsgType", 15 },
  { "ActionPutAllflowMsgType", 14 },
  { "ActionPutMultiflowAckMsgType", 10 },
  { "ActionPutMultiflowMsgType", 9 },
  { "ActionPutPerflowAckMsgType", 5 },
  { "ActionPutPerflowMsgType", 4 },
  { "ActionShareStateType", 16 },
  { "ActionStateType", 3 },
  { "SynType", 0 },
};
const ProtobufCEnumDescriptor my_action_message__data_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MyActionMessage.DataType",
  "DataType",
  "MyActionMessage__DataType",
  "",
  17,
  my_action_message__data_type__enum_values_by_number,
  17,
  my_action_message__data_type__enum_values_by_name,
  2,
  my_action_message__data_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor my_action_message__field_descriptors[18] =
{
  {
    "data_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MyActionMessage, data_type),
    &my_action_message__data_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionsyn",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionsyn),
    &action_syn__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetPerflowMsg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetperflowmsg),
    &action_get_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetPerflowAckMsg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetperflowackmsg),
    &action_get_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionState",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionstate),
    &action_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutPerflowMsg",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputperflowmsg),
    &action_put_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutPerflowAckMsg",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputperflowackmsg),
    &action_put_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetMultiflowMsg",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetmultiflowmsg),
    &action_get_multiflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetMultiflowAckMsg",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetmultiflowackmsg),
    &action_get_multiflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionMultiState",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionmultistate),
    &action_multi_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutMultiflowMsg",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputmultiflowmsg),
    &action_put_multiflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutMultiflowAckMsg",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputmultiflowackmsg),
    &action_put_multiflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetAllflowMsg",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetallflowmsg),
    &action_get_allflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetAllflowAckMsg",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetallflowackmsg),
    &action_get_allflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionAllState",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionallstate),
    &action_all_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutAllflowMsg",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputallflowmsg),
    &action_put_allflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutAllflowAckMsg",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputallflowackmsg),
    &action_put_allflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shareState",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, sharestate),
    &share_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned my_action_message__field_indices_by_name[] = {
  14,   /* field[14] = actionAllState */
  13,   /* field[13] = actionGetAllflowAckMsg */
  12,   /* field[12] = actionGetAllflowMsg */
  8,   /* field[8] = actionGetMultiflowAckMsg */
  7,   /* field[7] = actionGetMultiflowMsg */
  3,   /* field[3] = actionGetPerflowAckMsg */
  2,   /* field[2] = actionGetPerflowMsg */
  9,   /* field[9] = actionMultiState */
  16,   /* field[16] = actionPutAllflowAckMsg */
  15,   /* field[15] = actionPutAllflowMsg */
  11,   /* field[11] = actionPutMultiflowAckMsg */
  10,   /* field[10] = actionPutMultiflowMsg */
  6,   /* field[6] = actionPutPerflowAckMsg */
  5,   /* field[5] = actionPutPerflowMsg */
  4,   /* field[4] = actionState */
  1,   /* field[1] = actionsyn */
  0,   /* field[0] = data_type */
  17,   /* field[17] = shareState */
};
static const ProtobufCIntRange my_action_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor my_action_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MyActionMessage",
  "MyActionMessage",
  "MyActionMessage",
  "",
  sizeof(MyActionMessage),
  18,
  my_action_message__field_descriptors,
  my_action_message__field_indices_by_name,
  1,  my_action_message__number_ranges,
  (ProtobufCMessageInit) my_action_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_syn__field_descriptors[2] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionSyn, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionSyn, has_pid),
    offsetof(ActionSyn, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_syn__field_indices_by_name[] = {
  0,   /* field[0] = host */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange action_syn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_syn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionSyn",
  "ActionSyn",
  "ActionSyn",
  "",
  sizeof(ActionSyn),
  2,
  action_syn__field_descriptors,
  action_syn__field_indices_by_name,
  1,  action_syn__number_ranges,
  (ProtobufCMessageInit) action_syn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue action_state__fw_state__enum_values_by_number[2] =
{
  { "OPEN", "ACTION_STATE__FW_STATE__OPEN", 1 },
  { "CLOSED", "ACTION_STATE__FW_STATE__CLOSED", 2 },
};
static const ProtobufCIntRange action_state__fw_state__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex action_state__fw_state__enum_values_by_name[2] =
{
  { "CLOSED", 1 },
  { "OPEN", 0 },
};
const ProtobufCEnumDescriptor action_state__fw_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ActionState.fwState",
  "fwState",
  "ActionState__FwState",
  "",
  2,
  action_state__fw_state__enum_values_by_number,
  2,
  action_state__fw_state__enum_values_by_name,
  1,
  action_state__fw_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor action_state__field_descriptors[20] =
{
  {
    "start_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_start_time),
    offsetof(ActionState, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_pkt_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_last_pkt_time),
    offsetof(ActionState, last_pkt_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_cxid),
    offsetof(ActionState, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reversed",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_reversed),
    offsetof(ActionState, reversed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "af",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionState, has_af),
    offsetof(ActionState, af),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_total_pkts",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_s_total_pkts),
    offsetof(ActionState, s_total_pkts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_total_bytes",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_s_total_bytes),
    offsetof(ActionState, s_total_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_total_pkts",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_d_total_pkts),
    offsetof(ActionState, d_total_pkts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_total_bytes",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_d_total_bytes),
    offsetof(ActionState, d_total_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_tcpFlags",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_s_tcpflags),
    offsetof(ActionState, s_tcpflags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pad",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_pad),
    offsetof(ActionState, pad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_tcpFlags",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_d_tcpflags),
    offsetof(ActionState, d_tcpflags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "check",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_check),
    offsetof(ActionState, check),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionState, has_hash),
    offsetof(ActionState, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_asset",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionState, c_asset),
    &asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_asset",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionState, s_asset),
    &asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fwstate",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ActionState, has_fwstate),
    offsetof(ActionState, fwstate),
    &action_state__fw_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "external_ip",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionState, has_external_ip),
    offsetof(ActionState, external_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "external_port",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionState, has_external_port),
    offsetof(ActionState, external_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nat_hash",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionState, has_nat_hash),
    offsetof(ActionState, nat_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_state__field_indices_by_name[] = {
  4,   /* field[4] = af */
  14,   /* field[14] = c_asset */
  12,   /* field[12] = check */
  2,   /* field[2] = cxid */
  11,   /* field[11] = d_tcpFlags */
  8,   /* field[8] = d_total_bytes */
  7,   /* field[7] = d_total_pkts */
  17,   /* field[17] = external_ip */
  18,   /* field[18] = external_port */
  16,   /* field[16] = fwstate */
  13,   /* field[13] = hash */
  1,   /* field[1] = last_pkt_time */
  19,   /* field[19] = nat_hash */
  10,   /* field[10] = pad */
  3,   /* field[3] = reversed */
  15,   /* field[15] = s_asset */
  9,   /* field[9] = s_tcpFlags */
  6,   /* field[6] = s_total_bytes */
  5,   /* field[5] = s_total_pkts */
  0,   /* field[0] = start_time */
};
static const ProtobufCIntRange action_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 20 }
};
const ProtobufCMessageDescriptor action_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionState",
  "ActionState",
  "ActionState",
  "",
  sizeof(ActionState),
  20,
  action_state__field_descriptors,
  action_state__field_indices_by_name,
  1,  action_state__number_ranges,
  (ProtobufCMessageInit) action_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue share_state__fw_state__enum_values_by_number[2] =
{
  { "OPEN", "SHARE_STATE__FW_STATE__OPEN", 1 },
  { "CLOSED", "SHARE_STATE__FW_STATE__CLOSED", 2 },
};
static const ProtobufCIntRange share_state__fw_state__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex share_state__fw_state__enum_values_by_name[2] =
{
  { "CLOSED", 1 },
  { "OPEN", 0 },
};
const ProtobufCEnumDescriptor share_state__fw_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ShareState.fwState",
  "fwState",
  "ShareState__FwState",
  "",
  2,
  share_state__fw_state__enum_values_by_number,
  2,
  share_state__fw_state__enum_values_by_name,
  1,
  share_state__fw_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor share_state__field_descriptors[25] =
{
  {
    "start_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ShareState, has_start_time),
    offsetof(ShareState, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_pkt_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ShareState, has_last_pkt_time),
    offsetof(ShareState, last_pkt_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ShareState, has_cxid),
    offsetof(ShareState, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reversed",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShareState, has_reversed),
    offsetof(ShareState, reversed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "af",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ShareState, has_af),
    offsetof(ShareState, af),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hw_proto",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ShareState, has_hw_proto),
    offsetof(ShareState, hw_proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ShareState, has_proto),
    offsetof(ShareState, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_ip",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ShareState, has_s_ip),
    offsetof(ShareState, s_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_ip",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ShareState, has_d_ip),
    offsetof(ShareState, d_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_port",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ShareState, has_s_port),
    offsetof(ShareState, s_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_port",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ShareState, has_d_port),
    offsetof(ShareState, d_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_total_pkts",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ShareState, has_s_total_pkts),
    offsetof(ShareState, s_total_pkts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_total_bytes",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ShareState, has_s_total_bytes),
    offsetof(ShareState, s_total_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_total_pkts",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ShareState, has_d_total_pkts),
    offsetof(ShareState, d_total_pkts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_total_bytes",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ShareState, has_d_total_bytes),
    offsetof(ShareState, d_total_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_tcpFlags",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShareState, has_s_tcpflags),
    offsetof(ShareState, s_tcpflags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pad",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShareState, has_pad),
    offsetof(ShareState, pad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_tcpFlags",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShareState, has_d_tcpflags),
    offsetof(ShareState, d_tcpflags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "check",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShareState, has_check),
    offsetof(ShareState, check),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_asset",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShareState, c_asset),
    &asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_asset",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShareState, s_asset),
    &asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fwstate",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ShareState, has_fwstate),
    offsetof(ShareState, fwstate),
    &share_state__fw_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "external_ip",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ShareState, has_external_ip),
    offsetof(ShareState, external_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "external_port",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ShareState, has_external_port),
    offsetof(ShareState, external_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ShareState, has_hash),
    offsetof(ShareState, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned share_state__field_indices_by_name[] = {
  4,   /* field[4] = af */
  19,   /* field[19] = c_asset */
  18,   /* field[18] = check */
  2,   /* field[2] = cxid */
  8,   /* field[8] = d_ip */
  10,   /* field[10] = d_port */
  17,   /* field[17] = d_tcpFlags */
  14,   /* field[14] = d_total_bytes */
  13,   /* field[13] = d_total_pkts */
  22,   /* field[22] = external_ip */
  23,   /* field[23] = external_port */
  21,   /* field[21] = fwstate */
  24,   /* field[24] = hash */
  5,   /* field[5] = hw_proto */
  1,   /* field[1] = last_pkt_time */
  16,   /* field[16] = pad */
  6,   /* field[6] = proto */
  3,   /* field[3] = reversed */
  20,   /* field[20] = s_asset */
  7,   /* field[7] = s_ip */
  9,   /* field[9] = s_port */
  15,   /* field[15] = s_tcpFlags */
  12,   /* field[12] = s_total_bytes */
  11,   /* field[11] = s_total_pkts */
  0,   /* field[0] = start_time */
};
static const ProtobufCIntRange share_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 25 }
};
const ProtobufCMessageDescriptor share_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShareState",
  "ShareState",
  "ShareState",
  "",
  sizeof(ShareState),
  25,
  share_state__field_descriptors,
  share_state__field_indices_by_name,
  1,  share_state__number_ranges,
  (ProtobufCMessageInit) share_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_perflow_msg__field_descriptors[3] =
{
  {
    "hw_proto",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionGetPerflowMsg, has_hw_proto),
    offsetof(ActionGetPerflowMsg, hw_proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionGetPerflowMsg, has_proto),
    offsetof(ActionGetPerflowMsg, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "share",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionGetPerflowMsg, has_share),
    offsetof(ActionGetPerflowMsg, share),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = hw_proto */
  1,   /* field[1] = proto */
  2,   /* field[2] = share */
};
static const ProtobufCIntRange action_get_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor action_get_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetPerflowMsg",
  "ActionGetPerflowMsg",
  "ActionGetPerflowMsg",
  "",
  sizeof(ActionGetPerflowMsg),
  3,
  action_get_perflow_msg__field_descriptors,
  action_get_perflow_msg__field_indices_by_name,
  1,  action_get_perflow_msg__number_ranges,
  (ProtobufCMessageInit) action_get_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_perflow_ack_msg__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionGetPerflowAckMsg, has_count),
    offsetof(ActionGetPerflowAckMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_perflow_ack_msg__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange action_get_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_get_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetPerflowAckMsg",
  "ActionGetPerflowAckMsg",
  "ActionGetPerflowAckMsg",
  "",
  sizeof(ActionGetPerflowAckMsg),
  1,
  action_get_perflow_ack_msg__field_descriptors,
  action_get_perflow_ack_msg__field_indices_by_name,
  1,  action_get_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_get_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_perflow_msg__field_descriptors[2] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionPutPerflowMsg, state),
    &action_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "share_state",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionPutPerflowMsg, share_state),
    &share_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_perflow_msg__field_indices_by_name[] = {
  1,   /* field[1] = share_state */
  0,   /* field[0] = state */
};
static const ProtobufCIntRange action_put_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_put_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "",
  sizeof(ActionPutPerflowMsg),
  2,
  action_put_perflow_msg__field_descriptors,
  action_put_perflow_msg__field_indices_by_name,
  1,  action_put_perflow_msg__number_ranges,
  (ProtobufCMessageInit) action_put_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_perflow_ack_msg__field_descriptors[2] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionPutPerflowAckMsg, has_hash),
    offsetof(ActionPutPerflowAckMsg, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionPutPerflowAckMsg, has_cxid),
    offsetof(ActionPutPerflowAckMsg, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_perflow_ack_msg__field_indices_by_name[] = {
  1,   /* field[1] = cxid */
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange action_put_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_put_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutPerflowAckMsg",
  "ActionPutPerflowAckMsg",
  "ActionPutPerflowAckMsg",
  "",
  sizeof(ActionPutPerflowAckMsg),
  2,
  action_put_perflow_ack_msg__field_descriptors,
  action_put_perflow_ack_msg__field_indices_by_name,
  1,  action_put_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_put_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define action_get_multiflow_msg__field_descriptors NULL
#define action_get_multiflow_msg__field_indices_by_name NULL
#define action_get_multiflow_msg__number_ranges NULL
const ProtobufCMessageDescriptor action_get_multiflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetMultiflowMsg",
  "ActionGetMultiflowMsg",
  "ActionGetMultiflowMsg",
  "",
  sizeof(ActionGetMultiflowMsg),
  0,
  action_get_multiflow_msg__field_descriptors,
  action_get_multiflow_msg__field_indices_by_name,
  0,  action_get_multiflow_msg__number_ranges,
  (ProtobufCMessageInit) action_get_multiflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_multiflow_ack_msg__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionGetMultiflowAckMsg, has_count),
    offsetof(ActionGetMultiflowAckMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_multiflow_ack_msg__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange action_get_multiflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_get_multiflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetMultiflowAckMsg",
  "ActionGetMultiflowAckMsg",
  "ActionGetMultiflowAckMsg",
  "",
  sizeof(ActionGetMultiflowAckMsg),
  1,
  action_get_multiflow_ack_msg__field_descriptors,
  action_get_multiflow_ack_msg__field_indices_by_name,
  1,  action_get_multiflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_get_multiflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_multi_state__field_descriptors[1] =
{
  {
    "multi_state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionMultiState, multi_state),
    &asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_multi_state__field_indices_by_name[] = {
  0,   /* field[0] = multi_state */
};
static const ProtobufCIntRange action_multi_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_multi_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionMultiState",
  "ActionMultiState",
  "ActionMultiState",
  "",
  sizeof(ActionMultiState),
  1,
  action_multi_state__field_descriptors,
  action_multi_state__field_indices_by_name,
  1,  action_multi_state__number_ranges,
  (ProtobufCMessageInit) action_multi_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_multiflow_msg__field_descriptors[1] =
{
  {
    "multi_state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionPutMultiflowMsg, multi_state),
    &action_multi_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_multiflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = multi_state */
};
static const ProtobufCIntRange action_put_multiflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_put_multiflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutMultiflowMsg",
  "ActionPutMultiflowMsg",
  "ActionPutMultiflowMsg",
  "",
  sizeof(ActionPutMultiflowMsg),
  1,
  action_put_multiflow_msg__field_descriptors,
  action_put_multiflow_msg__field_indices_by_name,
  1,  action_put_multiflow_msg__number_ranges,
  (ProtobufCMessageInit) action_put_multiflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define action_put_multiflow_ack_msg__field_descriptors NULL
#define action_put_multiflow_ack_msg__field_indices_by_name NULL
#define action_put_multiflow_ack_msg__number_ranges NULL
const ProtobufCMessageDescriptor action_put_multiflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutMultiflowAckMsg",
  "ActionPutMultiflowAckMsg",
  "ActionPutMultiflowAckMsg",
  "",
  sizeof(ActionPutMultiflowAckMsg),
  0,
  action_put_multiflow_ack_msg__field_descriptors,
  action_put_multiflow_ack_msg__field_indices_by_name,
  0,  action_put_multiflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_put_multiflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define action_get_allflow_msg__field_descriptors NULL
#define action_get_allflow_msg__field_indices_by_name NULL
#define action_get_allflow_msg__number_ranges NULL
const ProtobufCMessageDescriptor action_get_allflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetAllflowMsg",
  "ActionGetAllflowMsg",
  "ActionGetAllflowMsg",
  "",
  sizeof(ActionGetAllflowMsg),
  0,
  action_get_allflow_msg__field_descriptors,
  action_get_allflow_msg__field_indices_by_name,
  0,  action_get_allflow_msg__number_ranges,
  (ProtobufCMessageInit) action_get_allflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_allflow_ack_msg__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionGetAllflowAckMsg, has_count),
    offsetof(ActionGetAllflowAckMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_allflow_ack_msg__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange action_get_allflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_get_allflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetAllflowAckMsg",
  "ActionGetAllflowAckMsg",
  "ActionGetAllflowAckMsg",
  "",
  sizeof(ActionGetAllflowAckMsg),
  1,
  action_get_allflow_ack_msg__field_descriptors,
  action_get_allflow_ack_msg__field_indices_by_name,
  1,  action_get_allflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_get_allflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_all_state__field_descriptors[1] =
{
  {
    "all_state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionAllState, all_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_all_state__field_indices_by_name[] = {
  0,   /* field[0] = all_state */
};
static const ProtobufCIntRange action_all_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_all_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionAllState",
  "ActionAllState",
  "ActionAllState",
  "",
  sizeof(ActionAllState),
  1,
  action_all_state__field_descriptors,
  action_all_state__field_indices_by_name,
  1,  action_all_state__number_ranges,
  (ProtobufCMessageInit) action_all_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_allflow_msg__field_descriptors[1] =
{
  {
    "all_state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionPutAllflowMsg, all_state),
    &action_all_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_allflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = all_state */
};
static const ProtobufCIntRange action_put_allflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_put_allflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutAllflowMsg",
  "ActionPutAllflowMsg",
  "ActionPutAllflowMsg",
  "",
  sizeof(ActionPutAllflowMsg),
  1,
  action_put_allflow_msg__field_descriptors,
  action_put_allflow_msg__field_indices_by_name,
  1,  action_put_allflow_msg__number_ranges,
  (ProtobufCMessageInit) action_put_allflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define action_put_allflow_ack_msg__field_descriptors NULL
#define action_put_allflow_ack_msg__field_indices_by_name NULL
#define action_put_allflow_ack_msg__number_ranges NULL
const ProtobufCMessageDescriptor action_put_allflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutAllflowAckMsg",
  "ActionPutAllflowAckMsg",
  "ActionPutAllflowAckMsg",
  "",
  sizeof(ActionPutAllflowAckMsg),
  0,
  action_put_allflow_ack_msg__field_descriptors,
  action_put_allflow_ack_msg__field_indices_by_name,
  0,  action_put_allflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_put_allflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor asset__field_descriptors[8] =
{
  {
    "first_seen",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(Asset, has_first_seen),
    offsetof(Asset, first_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_seen",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(Asset, has_last_seen),
    offsetof(Asset, last_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i_attempts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Asset, has_i_attempts),
    offsetof(Asset, i_attempts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "af",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Asset, has_af),
    offsetof(Asset, af),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlan",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Asset, has_vlan),
    offsetof(Asset, vlan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_ip",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Asset, has_s_ip),
    offsetof(Asset, s_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "services",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Asset, services),
    &serv_asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Asset, os),
    &os_asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned asset__field_indices_by_name[] = {
  3,   /* field[3] = af */
  0,   /* field[0] = first_seen */
  2,   /* field[2] = i_attempts */
  1,   /* field[1] = last_seen */
  7,   /* field[7] = os */
  5,   /* field[5] = s_ip */
  6,   /* field[6] = services */
  4,   /* field[4] = vlan */
};
static const ProtobufCIntRange asset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor asset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Asset",
  "Asset",
  "Asset",
  "",
  sizeof(Asset),
  8,
  asset__field_descriptors,
  asset__field_indices_by_name,
  1,  asset__number_ranges,
  (ProtobufCMessageInit) asset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor serv_asset__field_descriptors[10] =
{
  {
    "first_seen",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ServAsset, has_first_seen),
    offsetof(ServAsset, first_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_seen",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ServAsset, has_last_seen),
    offsetof(ServAsset, last_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i_attempts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ServAsset, has_i_attempts),
    offsetof(ServAsset, i_attempts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ServAsset, has_proto),
    offsetof(ServAsset, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ServAsset, has_port),
    offsetof(ServAsset, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttl",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ServAsset, has_ttl),
    offsetof(ServAsset, ttl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bservice",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ServAsset, bservice),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bapplication",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ServAsset, bapplication),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "role",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ServAsset, has_role),
    offsetof(ServAsset, role),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unknown",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ServAsset, has_unknown),
    offsetof(ServAsset, unknown),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned serv_asset__field_indices_by_name[] = {
  7,   /* field[7] = bapplication */
  6,   /* field[6] = bservice */
  0,   /* field[0] = first_seen */
  2,   /* field[2] = i_attempts */
  1,   /* field[1] = last_seen */
  4,   /* field[4] = port */
  3,   /* field[3] = proto */
  8,   /* field[8] = role */
  5,   /* field[5] = ttl */
  9,   /* field[9] = unknown */
};
static const ProtobufCIntRange serv_asset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor serv_asset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServAsset",
  "ServAsset",
  "ServAsset",
  "",
  sizeof(ServAsset),
  10,
  serv_asset__field_descriptors,
  serv_asset__field_indices_by_name,
  1,  serv_asset__number_ranges,
  (ProtobufCMessageInit) serv_asset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor os_asset__field_descriptors[14] =
{
  {
    "first_seen",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(OsAsset, has_first_seen),
    offsetof(OsAsset, first_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_seen",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(OsAsset, has_last_seen),
    offsetof(OsAsset, last_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i_attempts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_i_attempts),
    offsetof(OsAsset, i_attempts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bvendor",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OsAsset, bvendor),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bos",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OsAsset, bos),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detection",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_detection),
    offsetof(OsAsset, detection),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raw_fp",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OsAsset, raw_fp),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "matched_fp",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OsAsset, matched_fp),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_os",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OsAsset, match_os),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_desc",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OsAsset, match_desc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_port),
    offsetof(OsAsset, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtu",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_mtu),
    offsetof(OsAsset, mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttl",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_ttl),
    offsetof(OsAsset, ttl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_uptime),
    offsetof(OsAsset, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned os_asset__field_indices_by_name[] = {
  4,   /* field[4] = bos */
  3,   /* field[3] = bvendor */
  5,   /* field[5] = detection */
  0,   /* field[0] = first_seen */
  2,   /* field[2] = i_attempts */
  1,   /* field[1] = last_seen */
  9,   /* field[9] = match_desc */
  8,   /* field[8] = match_os */
  7,   /* field[7] = matched_fp */
  11,   /* field[11] = mtu */
  10,   /* field[10] = port */
  6,   /* field[6] = raw_fp */
  12,   /* field[12] = ttl */
  13,   /* field[13] = uptime */
};
static const ProtobufCIntRange os_asset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor os_asset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OsAsset",
  "OsAsset",
  "OsAsset",
  "",
  sizeof(OsAsset),
  14,
  os_asset__field_descriptors,
  os_asset__field_indices_by_name,
  1,  os_asset__number_ranges,
  (ProtobufCMessageInit) os_asset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bstring__field_descriptors[3] =
{
  {
    "mlen",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Bstring, has_mlen),
    offsetof(Bstring, mlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slen",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Bstring, has_slen),
    offsetof(Bstring, slen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Bstring, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bstring__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = mlen */
  1,   /* field[1] = slen */
};
static const ProtobufCIntRange bstring__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bstring__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Bstring",
  "Bstring",
  "Bstring",
  "",
  sizeof(Bstring),
  3,
  bstring__field_descriptors,
  bstring__field_indices_by_name,
  1,  bstring__number_ranges,
  (ProtobufCMessageInit) bstring__init,
  NULL,NULL,NULL    /* reserved[123] */
};
