/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: getPerflowAckMsg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "getPerflowAckMsg.pb-c.h"
void   get_perflow_ack_msg__init
                     (GetPerflowAckMsg         *message)
{
  static const GetPerflowAckMsg init_value = GET_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t get_perflow_ack_msg__get_packed_size
                     (const GetPerflowAckMsg *message)
{
  assert(message->base.descriptor == &get_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_perflow_ack_msg__pack
                     (const GetPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_perflow_ack_msg__pack_to_buffer
                     (const GetPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetPerflowAckMsg *
       get_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetPerflowAckMsg *)
     protobuf_c_message_unpack (&get_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   get_perflow_ack_msg__free_unpacked
                     (GetPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor get_perflow_ack_msg__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetPerflowAckMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_perflow_ack_msg__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange get_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetPerflowAckMsg",
  "GetPerflowAckMsg",
  "GetPerflowAckMsg",
  "",
  sizeof(GetPerflowAckMsg),
  1,
  get_perflow_ack_msg__field_descriptors,
  get_perflow_ack_msg__field_indices_by_name,
  1,  get_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) get_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
