/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: struct.proto */

#ifndef PROTOBUF_C_struct_2eproto__INCLUDED
#define PROTOBUF_C_struct_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Struct Struct;


/* --- enums --- */


/* --- messages --- */

struct  _Struct
{
  ProtobufCMessage base;
  uint32_t a;
  uint32_t b;
  uint32_t c;
  uint32_t d;
  uint32_t e;
  uint32_t f;
  uint32_t g;
  uint32_t h;
  uint32_t i;
  uint32_t j;
  uint32_t k;
  uint32_t l;
};
#define STRUCT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&struct__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Struct methods */
void   struct__init
                     (Struct         *message);
size_t struct__get_packed_size
                     (const Struct   *message);
size_t struct__pack
                     (const Struct   *message,
                      uint8_t             *out);
size_t struct__pack_to_buffer
                     (const Struct   *message,
                      ProtobufCBuffer     *buffer);
Struct *
       struct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   struct__free_unpacked
                     (Struct *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Struct_Closure)
                 (const Struct *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor struct__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_struct_2eproto__INCLUDED */
