/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: myActionMessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "myActionMessage.pb-c.h"
void   my_action_message__init
                     (MyActionMessage         *message)
{
  static const MyActionMessage init_value = MY_ACTION_MESSAGE__INIT;
  *message = init_value;
}
size_t my_action_message__get_packed_size
                     (const MyActionMessage *message)
{
  assert(message->base.descriptor == &my_action_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t my_action_message__pack
                     (const MyActionMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &my_action_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t my_action_message__pack_to_buffer
                     (const MyActionMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &my_action_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MyActionMessage *
       my_action_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MyActionMessage *)
     protobuf_c_message_unpack (&my_action_message__descriptor,
                                allocator, len, data);
}
void   my_action_message__free_unpacked
                     (MyActionMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &my_action_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_syn__init
                     (ActionSyn         *message)
{
  static const ActionSyn init_value = ACTION_SYN__INIT;
  *message = init_value;
}
size_t action_syn__get_packed_size
                     (const ActionSyn *message)
{
  assert(message->base.descriptor == &action_syn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_syn__pack
                     (const ActionSyn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_syn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_syn__pack_to_buffer
                     (const ActionSyn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_syn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionSyn *
       action_syn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionSyn *)
     protobuf_c_message_unpack (&action_syn__descriptor,
                                allocator, len, data);
}
void   action_syn__free_unpacked
                     (ActionSyn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_syn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_perflow_msg__init
                     (ActionGetPerflowMsg         *message)
{
  static const ActionGetPerflowMsg init_value = ACTION_GET_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_get_perflow_msg__get_packed_size
                     (const ActionGetPerflowMsg *message)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_perflow_msg__pack
                     (const ActionGetPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_perflow_msg__pack_to_buffer
                     (const ActionGetPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetPerflowMsg *
       action_get_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetPerflowMsg *)
     protobuf_c_message_unpack (&action_get_perflow_msg__descriptor,
                                allocator, len, data);
}
void   action_get_perflow_msg__free_unpacked
                     (ActionGetPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_perflow_ack_msg__init
                     (ActionGetPerflowAckMsg         *message)
{
  static const ActionGetPerflowAckMsg init_value = ACTION_GET_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_get_perflow_ack_msg__get_packed_size
                     (const ActionGetPerflowAckMsg *message)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_perflow_ack_msg__pack
                     (const ActionGetPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_perflow_ack_msg__pack_to_buffer
                     (const ActionGetPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetPerflowAckMsg *
       action_get_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetPerflowAckMsg *)
     protobuf_c_message_unpack (&action_get_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_get_perflow_ack_msg__free_unpacked
                     (ActionGetPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_state__init
                     (ActionState         *message)
{
  static const ActionState init_value = ACTION_STATE__INIT;
  *message = init_value;
}
size_t action_state__get_packed_size
                     (const ActionState *message)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_state__pack
                     (const ActionState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_state__pack_to_buffer
                     (const ActionState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionState *
       action_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionState *)
     protobuf_c_message_unpack (&action_state__descriptor,
                                allocator, len, data);
}
void   action_state__free_unpacked
                     (ActionState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_perflow_msg__init
                     (ActionPutPerflowMsg         *message)
{
  static const ActionPutPerflowMsg init_value = ACTION_PUT_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_put_perflow_msg__get_packed_size
                     (const ActionPutPerflowMsg *message)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_perflow_msg__pack
                     (const ActionPutPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_perflow_msg__pack_to_buffer
                     (const ActionPutPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutPerflowMsg *
       action_put_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutPerflowMsg *)
     protobuf_c_message_unpack (&action_put_perflow_msg__descriptor,
                                allocator, len, data);
}
void   action_put_perflow_msg__free_unpacked
                     (ActionPutPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_perflow_ack_msg__init
                     (ActionPutPerflowAckMsg         *message)
{
  static const ActionPutPerflowAckMsg init_value = ACTION_PUT_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_put_perflow_ack_msg__get_packed_size
                     (const ActionPutPerflowAckMsg *message)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_perflow_ack_msg__pack
                     (const ActionPutPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_perflow_ack_msg__pack_to_buffer
                     (const ActionPutPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutPerflowAckMsg *
       action_put_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutPerflowAckMsg *)
     protobuf_c_message_unpack (&action_put_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_put_perflow_ack_msg__free_unpacked
                     (ActionPutPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   asset__init
                     (Asset         *message)
{
  static const Asset init_value = ASSET__INIT;
  *message = init_value;
}
size_t asset__get_packed_size
                     (const Asset *message)
{
  assert(message->base.descriptor == &asset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t asset__pack
                     (const Asset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &asset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t asset__pack_to_buffer
                     (const Asset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &asset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Asset *
       asset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Asset *)
     protobuf_c_message_unpack (&asset__descriptor,
                                allocator, len, data);
}
void   asset__free_unpacked
                     (Asset *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &asset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   serv_asset__init
                     (ServAsset         *message)
{
  static const ServAsset init_value = SERV_ASSET__INIT;
  *message = init_value;
}
size_t serv_asset__get_packed_size
                     (const ServAsset *message)
{
  assert(message->base.descriptor == &serv_asset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t serv_asset__pack
                     (const ServAsset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &serv_asset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t serv_asset__pack_to_buffer
                     (const ServAsset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &serv_asset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServAsset *
       serv_asset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServAsset *)
     protobuf_c_message_unpack (&serv_asset__descriptor,
                                allocator, len, data);
}
void   serv_asset__free_unpacked
                     (ServAsset *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &serv_asset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   os_asset__init
                     (OsAsset         *message)
{
  static const OsAsset init_value = OS_ASSET__INIT;
  *message = init_value;
}
size_t os_asset__get_packed_size
                     (const OsAsset *message)
{
  assert(message->base.descriptor == &os_asset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t os_asset__pack
                     (const OsAsset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &os_asset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t os_asset__pack_to_buffer
                     (const OsAsset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &os_asset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OsAsset *
       os_asset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OsAsset *)
     protobuf_c_message_unpack (&os_asset__descriptor,
                                allocator, len, data);
}
void   os_asset__free_unpacked
                     (OsAsset *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &os_asset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bstring__init
                     (Bstring         *message)
{
  static const Bstring init_value = BSTRING__INIT;
  *message = init_value;
}
size_t bstring__get_packed_size
                     (const Bstring *message)
{
  assert(message->base.descriptor == &bstring__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bstring__pack
                     (const Bstring *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bstring__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bstring__pack_to_buffer
                     (const Bstring *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bstring__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bstring *
       bstring__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bstring *)
     protobuf_c_message_unpack (&bstring__descriptor,
                                allocator, len, data);
}
void   bstring__free_unpacked
                     (Bstring *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bstring__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue my_action_message__data_type__enum_values_by_number[6] =
{
  { "SynType", "MY_ACTION_MESSAGE__DATA_TYPE__SynType", 1 },
  { "ActionGetPerflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetPerflowMsgType", 2 },
  { "ActionGetPerflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetPerflowAckMsgType", 3 },
  { "ActionStateType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionStateType", 4 },
  { "ActionPutPerflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutPerflowMsgType", 5 },
  { "ActionPutPerflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutPerflowAckMsgType", 6 },
};
static const ProtobufCIntRange my_action_message__data_type__value_ranges[] = {
{1, 0},{0, 6}
};
static const ProtobufCEnumValueIndex my_action_message__data_type__enum_values_by_name[6] =
{
  { "ActionGetPerflowAckMsgType", 2 },
  { "ActionGetPerflowMsgType", 1 },
  { "ActionPutPerflowAckMsgType", 5 },
  { "ActionPutPerflowMsgType", 4 },
  { "ActionStateType", 3 },
  { "SynType", 0 },
};
const ProtobufCEnumDescriptor my_action_message__data_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MyActionMessage.DataType",
  "DataType",
  "MyActionMessage__DataType",
  "",
  6,
  my_action_message__data_type__enum_values_by_number,
  6,
  my_action_message__data_type__enum_values_by_name,
  1,
  my_action_message__data_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor my_action_message__field_descriptors[7] =
{
  {
    "data_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MyActionMessage, data_type),
    &my_action_message__data_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionsyn",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionsyn),
    &action_syn__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetPerflowMsg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetperflowmsg),
    &action_get_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetPerflowAckMsg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetperflowackmsg),
    &action_get_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionState",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionstate),
    &action_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutPerflowMsg",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputperflowmsg),
    &action_put_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutPerflowAckMsg",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputperflowackmsg),
    &action_put_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned my_action_message__field_indices_by_name[] = {
  3,   /* field[3] = actionGetPerflowAckMsg */
  2,   /* field[2] = actionGetPerflowMsg */
  6,   /* field[6] = actionPutPerflowAckMsg */
  5,   /* field[5] = actionPutPerflowMsg */
  4,   /* field[4] = actionState */
  1,   /* field[1] = actionsyn */
  0,   /* field[0] = data_type */
};
static const ProtobufCIntRange my_action_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor my_action_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MyActionMessage",
  "MyActionMessage",
  "MyActionMessage",
  "",
  sizeof(MyActionMessage),
  7,
  my_action_message__field_descriptors,
  my_action_message__field_indices_by_name,
  1,  my_action_message__number_ranges,
  (ProtobufCMessageInit) my_action_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_syn__field_descriptors[2] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionSyn, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionSyn, has_pid),
    offsetof(ActionSyn, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_syn__field_indices_by_name[] = {
  0,   /* field[0] = host */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange action_syn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_syn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionSyn",
  "ActionSyn",
  "ActionSyn",
  "",
  sizeof(ActionSyn),
  2,
  action_syn__field_descriptors,
  action_syn__field_indices_by_name,
  1,  action_syn__number_ranges,
  (ProtobufCMessageInit) action_syn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_perflow_msg__field_descriptors[2] =
{
  {
    "hw_proto",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionGetPerflowMsg, has_hw_proto),
    offsetof(ActionGetPerflowMsg, hw_proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionGetPerflowMsg, has_proto),
    offsetof(ActionGetPerflowMsg, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = hw_proto */
  1,   /* field[1] = proto */
};
static const ProtobufCIntRange action_get_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_get_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetPerflowMsg",
  "ActionGetPerflowMsg",
  "ActionGetPerflowMsg",
  "",
  sizeof(ActionGetPerflowMsg),
  2,
  action_get_perflow_msg__field_descriptors,
  action_get_perflow_msg__field_indices_by_name,
  1,  action_get_perflow_msg__number_ranges,
  (ProtobufCMessageInit) action_get_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_perflow_ack_msg__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionGetPerflowAckMsg, has_count),
    offsetof(ActionGetPerflowAckMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_perflow_ack_msg__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange action_get_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_get_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetPerflowAckMsg",
  "ActionGetPerflowAckMsg",
  "ActionGetPerflowAckMsg",
  "",
  sizeof(ActionGetPerflowAckMsg),
  1,
  action_get_perflow_ack_msg__field_descriptors,
  action_get_perflow_ack_msg__field_indices_by_name,
  1,  action_get_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_get_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue action_state__fw_state__enum_values_by_number[2] =
{
  { "OPEN", "ACTION_STATE__FW_STATE__OPEN", 1 },
  { "CLOSED", "ACTION_STATE__FW_STATE__CLOSED", 2 },
};
static const ProtobufCIntRange action_state__fw_state__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex action_state__fw_state__enum_values_by_name[2] =
{
  { "CLOSED", 1 },
  { "OPEN", 0 },
};
const ProtobufCEnumDescriptor action_state__fw_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ActionState.fwState",
  "fwState",
  "ActionState__FwState",
  "",
  2,
  action_state__fw_state__enum_values_by_number,
  2,
  action_state__fw_state__enum_values_by_name,
  1,
  action_state__fw_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor action_state__field_descriptors[17] =
{
  {
    "start_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_start_time),
    offsetof(ActionState, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_pkt_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_last_pkt_time),
    offsetof(ActionState, last_pkt_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_cxid),
    offsetof(ActionState, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reversed",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_reversed),
    offsetof(ActionState, reversed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "af",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionState, has_af),
    offsetof(ActionState, af),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_total_pkts",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_s_total_pkts),
    offsetof(ActionState, s_total_pkts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_total_bytes",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_s_total_bytes),
    offsetof(ActionState, s_total_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_total_pkts",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_d_total_pkts),
    offsetof(ActionState, d_total_pkts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_total_bytes",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_d_total_bytes),
    offsetof(ActionState, d_total_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_tcpFlags",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_s_tcpflags),
    offsetof(ActionState, s_tcpflags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pad",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_pad),
    offsetof(ActionState, pad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_tcpFlags",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_d_tcpflags),
    offsetof(ActionState, d_tcpflags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "check",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ActionState, has_check),
    offsetof(ActionState, check),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionState, has_hash),
    offsetof(ActionState, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_asset",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionState, c_asset),
    &asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_asset",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionState, s_asset),
    &asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fwstate",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ActionState, has_fwstate),
    offsetof(ActionState, fwstate),
    &action_state__fw_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_state__field_indices_by_name[] = {
  4,   /* field[4] = af */
  14,   /* field[14] = c_asset */
  12,   /* field[12] = check */
  2,   /* field[2] = cxid */
  11,   /* field[11] = d_tcpFlags */
  8,   /* field[8] = d_total_bytes */
  7,   /* field[7] = d_total_pkts */
  16,   /* field[16] = fwstate */
  13,   /* field[13] = hash */
  1,   /* field[1] = last_pkt_time */
  10,   /* field[10] = pad */
  3,   /* field[3] = reversed */
  15,   /* field[15] = s_asset */
  9,   /* field[9] = s_tcpFlags */
  6,   /* field[6] = s_total_bytes */
  5,   /* field[5] = s_total_pkts */
  0,   /* field[0] = start_time */
};
static const ProtobufCIntRange action_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor action_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionState",
  "ActionState",
  "ActionState",
  "",
  sizeof(ActionState),
  17,
  action_state__field_descriptors,
  action_state__field_indices_by_name,
  1,  action_state__number_ranges,
  (ProtobufCMessageInit) action_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_perflow_msg__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionPutPerflowMsg, state),
    &action_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange action_put_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_put_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "",
  sizeof(ActionPutPerflowMsg),
  1,
  action_put_perflow_msg__field_descriptors,
  action_put_perflow_msg__field_indices_by_name,
  1,  action_put_perflow_msg__number_ranges,
  (ProtobufCMessageInit) action_put_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_perflow_ack_msg__field_descriptors[2] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionPutPerflowAckMsg, has_hash),
    offsetof(ActionPutPerflowAckMsg, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionPutPerflowAckMsg, has_cxid),
    offsetof(ActionPutPerflowAckMsg, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_perflow_ack_msg__field_indices_by_name[] = {
  1,   /* field[1] = cxid */
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange action_put_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_put_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutPerflowAckMsg",
  "ActionPutPerflowAckMsg",
  "ActionPutPerflowAckMsg",
  "",
  sizeof(ActionPutPerflowAckMsg),
  2,
  action_put_perflow_ack_msg__field_descriptors,
  action_put_perflow_ack_msg__field_indices_by_name,
  1,  action_put_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_put_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor asset__field_descriptors[8] =
{
  {
    "first_seen",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(Asset, has_first_seen),
    offsetof(Asset, first_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_seen",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(Asset, has_last_seen),
    offsetof(Asset, last_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i_attempts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Asset, has_i_attempts),
    offsetof(Asset, i_attempts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "af",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Asset, has_af),
    offsetof(Asset, af),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlan",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Asset, has_vlan),
    offsetof(Asset, vlan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_ip",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Asset, has_s_ip),
    offsetof(Asset, s_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "services",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Asset, services),
    &serv_asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Asset, os),
    &os_asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned asset__field_indices_by_name[] = {
  3,   /* field[3] = af */
  0,   /* field[0] = first_seen */
  2,   /* field[2] = i_attempts */
  1,   /* field[1] = last_seen */
  7,   /* field[7] = os */
  5,   /* field[5] = s_ip */
  6,   /* field[6] = services */
  4,   /* field[4] = vlan */
};
static const ProtobufCIntRange asset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor asset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Asset",
  "Asset",
  "Asset",
  "",
  sizeof(Asset),
  8,
  asset__field_descriptors,
  asset__field_indices_by_name,
  1,  asset__number_ranges,
  (ProtobufCMessageInit) asset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor serv_asset__field_descriptors[10] =
{
  {
    "first_seen",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ServAsset, has_first_seen),
    offsetof(ServAsset, first_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_seen",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ServAsset, has_last_seen),
    offsetof(ServAsset, last_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i_attempts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ServAsset, has_i_attempts),
    offsetof(ServAsset, i_attempts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ServAsset, has_proto),
    offsetof(ServAsset, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ServAsset, has_port),
    offsetof(ServAsset, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttl",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ServAsset, has_ttl),
    offsetof(ServAsset, ttl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bservice",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ServAsset, bservice),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bapplication",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ServAsset, bapplication),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "role",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ServAsset, has_role),
    offsetof(ServAsset, role),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unknown",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ServAsset, has_unknown),
    offsetof(ServAsset, unknown),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned serv_asset__field_indices_by_name[] = {
  7,   /* field[7] = bapplication */
  6,   /* field[6] = bservice */
  0,   /* field[0] = first_seen */
  2,   /* field[2] = i_attempts */
  1,   /* field[1] = last_seen */
  4,   /* field[4] = port */
  3,   /* field[3] = proto */
  8,   /* field[8] = role */
  5,   /* field[5] = ttl */
  9,   /* field[9] = unknown */
};
static const ProtobufCIntRange serv_asset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor serv_asset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServAsset",
  "ServAsset",
  "ServAsset",
  "",
  sizeof(ServAsset),
  10,
  serv_asset__field_descriptors,
  serv_asset__field_indices_by_name,
  1,  serv_asset__number_ranges,
  (ProtobufCMessageInit) serv_asset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor os_asset__field_descriptors[14] =
{
  {
    "first_seen",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(OsAsset, has_first_seen),
    offsetof(OsAsset, first_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_seen",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(OsAsset, has_last_seen),
    offsetof(OsAsset, last_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i_attempts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_i_attempts),
    offsetof(OsAsset, i_attempts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bvendor",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OsAsset, bvendor),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bos",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OsAsset, bos),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detection",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_detection),
    offsetof(OsAsset, detection),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raw_fp",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OsAsset, raw_fp),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "matched_fp",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OsAsset, matched_fp),
    &bstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_os",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OsAsset, match_os),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_desc",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OsAsset, match_desc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_port),
    offsetof(OsAsset, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtu",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_mtu),
    offsetof(OsAsset, mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttl",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_ttl),
    offsetof(OsAsset, ttl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(OsAsset, has_uptime),
    offsetof(OsAsset, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned os_asset__field_indices_by_name[] = {
  4,   /* field[4] = bos */
  3,   /* field[3] = bvendor */
  5,   /* field[5] = detection */
  0,   /* field[0] = first_seen */
  2,   /* field[2] = i_attempts */
  1,   /* field[1] = last_seen */
  9,   /* field[9] = match_desc */
  8,   /* field[8] = match_os */
  7,   /* field[7] = matched_fp */
  11,   /* field[11] = mtu */
  10,   /* field[10] = port */
  6,   /* field[6] = raw_fp */
  12,   /* field[12] = ttl */
  13,   /* field[13] = uptime */
};
static const ProtobufCIntRange os_asset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor os_asset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OsAsset",
  "OsAsset",
  "OsAsset",
  "",
  sizeof(OsAsset),
  14,
  os_asset__field_descriptors,
  os_asset__field_indices_by_name,
  1,  os_asset__number_ranges,
  (ProtobufCMessageInit) os_asset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bstring__field_descriptors[3] =
{
  {
    "mlen",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Bstring, has_mlen),
    offsetof(Bstring, mlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slen",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Bstring, has_slen),
    offsetof(Bstring, slen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Bstring, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bstring__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = mlen */
  1,   /* field[1] = slen */
};
static const ProtobufCIntRange bstring__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bstring__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Bstring",
  "Bstring",
  "Bstring",
  "",
  sizeof(Bstring),
  3,
  bstring__field_descriptors,
  bstring__field_indices_by_name,
  1,  bstring__number_ranges,
  (ProtobufCMessageInit) bstring__init,
  NULL,NULL,NULL    /* reserved[123] */
};
