/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: putPerflow.proto */

#ifndef PROTOBUF_C_putPerflow_2eproto__INCLUDED
#define PROTOBUF_C_putPerflow_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "flowstate.pb-c.h"

typedef struct _PutPerflowMsg PutPerflowMsg;


/* --- enums --- */


/* --- messages --- */

struct  _PutPerflowMsg
{
  ProtobufCMessage base;
  FlowState *state;
  uint32_t count;
};
#define PUT_PERFLOW_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&put_perflow_msg__descriptor) \
    , NULL, 0 }


/* PutPerflowMsg methods */
void   put_perflow_msg__init
                     (PutPerflowMsg         *message);
size_t put_perflow_msg__get_packed_size
                     (const PutPerflowMsg   *message);
size_t put_perflow_msg__pack
                     (const PutPerflowMsg   *message,
                      uint8_t             *out);
size_t put_perflow_msg__pack_to_buffer
                     (const PutPerflowMsg   *message,
                      ProtobufCBuffer     *buffer);
PutPerflowMsg *
       put_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   put_perflow_msg__free_unpacked
                     (PutPerflowMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PutPerflowMsg_Closure)
                 (const PutPerflowMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor put_perflow_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_putPerflow_2eproto__INCLUDED */
