/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: connPutPerflowAckMsg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "connPutPerflowAckMsg.pb-c.h"
void   conn_put_perflow_ack_msg__init
                     (ConnPutPerflowAckMsg         *message)
{
  static const ConnPutPerflowAckMsg init_value = CONN_PUT_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t conn_put_perflow_ack_msg__get_packed_size
                     (const ConnPutPerflowAckMsg *message)
{
  assert(message->base.descriptor == &conn_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conn_put_perflow_ack_msg__pack
                     (const ConnPutPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conn_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conn_put_perflow_ack_msg__pack_to_buffer
                     (const ConnPutPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conn_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnPutPerflowAckMsg *
       conn_put_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnPutPerflowAckMsg *)
     protobuf_c_message_unpack (&conn_put_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   conn_put_perflow_ack_msg__free_unpacked
                     (ConnPutPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conn_put_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor conn_put_perflow_ack_msg__field_descriptors[1] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(ConnPutPerflowAckMsg, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conn_put_perflow_ack_msg__field_indices_by_name[] = {
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange conn_put_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor conn_put_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnPutPerflowAckMsg",
  "ConnPutPerflowAckMsg",
  "ConnPutPerflowAckMsg",
  "",
  sizeof(ConnPutPerflowAckMsg),
  1,
  conn_put_perflow_ack_msg__field_descriptors,
  conn_put_perflow_ack_msg__field_indices_by_name,
  1,  conn_put_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) conn_put_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
