/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: connPutPerflowAckMsg.proto */

#ifndef PROTOBUF_C_connPutPerflowAckMsg_2eproto__INCLUDED
#define PROTOBUF_C_connPutPerflowAckMsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ConnPutPerflowAckMsg ConnPutPerflowAckMsg;


/* --- enums --- */


/* --- messages --- */

struct  _ConnPutPerflowAckMsg
{
  ProtobufCMessage base;
  uint32_t hash;
};
#define CONN_PUT_PERFLOW_ACK_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conn_put_perflow_ack_msg__descriptor) \
    , 0 }


/* ConnPutPerflowAckMsg methods */
void   conn_put_perflow_ack_msg__init
                     (ConnPutPerflowAckMsg         *message);
size_t conn_put_perflow_ack_msg__get_packed_size
                     (const ConnPutPerflowAckMsg   *message);
size_t conn_put_perflow_ack_msg__pack
                     (const ConnPutPerflowAckMsg   *message,
                      uint8_t             *out);
size_t conn_put_perflow_ack_msg__pack_to_buffer
                     (const ConnPutPerflowAckMsg   *message,
                      ProtobufCBuffer     *buffer);
ConnPutPerflowAckMsg *
       conn_put_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conn_put_perflow_ack_msg__free_unpacked
                     (ConnPutPerflowAckMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ConnPutPerflowAckMsg_Closure)
                 (const ConnPutPerflowAckMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor conn_put_perflow_ack_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_connPutPerflowAckMsg_2eproto__INCLUDED */
