/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: flowstate.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "flowstate.pb-c.h"
void   flow_state__init
                     (FlowState         *message)
{
  static const FlowState init_value = FLOW_STATE__INIT;
  *message = init_value;
}
size_t flow_state__get_packed_size
                     (const FlowState *message)
{
  assert(message->base.descriptor == &flow_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t flow_state__pack
                     (const FlowState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &flow_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t flow_state__pack_to_buffer
                     (const FlowState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &flow_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FlowState *
       flow_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FlowState *)
     protobuf_c_message_unpack (&flow_state__descriptor,
                                allocator, len, data);
}
void   flow_state__free_unpacked
                     (FlowState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &flow_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor flow_state__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FlowState, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned flow_state__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange flow_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor flow_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FlowState",
  "FlowState",
  "FlowState",
  "",
  sizeof(FlowState),
  1,
  flow_state__field_descriptors,
  flow_state__field_indices_by_name,
  1,  flow_state__number_ranges,
  (ProtobufCMessageInit) flow_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
