/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: myActionMessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "myActionMessage.pb-c.h"
void   my_action_message__init
                     (MyActionMessage         *message)
{
  static const MyActionMessage init_value = MY_ACTION_MESSAGE__INIT;
  *message = init_value;
}
size_t my_action_message__get_packed_size
                     (const MyActionMessage *message)
{
  assert(message->base.descriptor == &my_action_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t my_action_message__pack
                     (const MyActionMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &my_action_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t my_action_message__pack_to_buffer
                     (const MyActionMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &my_action_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MyActionMessage *
       my_action_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MyActionMessage *)
     protobuf_c_message_unpack (&my_action_message__descriptor,
                                allocator, len, data);
}
void   my_action_message__free_unpacked
                     (MyActionMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &my_action_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_syn__init
                     (ActionSyn         *message)
{
  static const ActionSyn init_value = ACTION_SYN__INIT;
  *message = init_value;
}
size_t action_syn__get_packed_size
                     (const ActionSyn *message)
{
  assert(message->base.descriptor == &action_syn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_syn__pack
                     (const ActionSyn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_syn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_syn__pack_to_buffer
                     (const ActionSyn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_syn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionSyn *
       action_syn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionSyn *)
     protobuf_c_message_unpack (&action_syn__descriptor,
                                allocator, len, data);
}
void   action_syn__free_unpacked
                     (ActionSyn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_syn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_perflow_msg__init
                     (ActionGetPerflowMsg         *message)
{
  static const ActionGetPerflowMsg init_value = ACTION_GET_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_get_perflow_msg__get_packed_size
                     (const ActionGetPerflowMsg *message)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_perflow_msg__pack
                     (const ActionGetPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_perflow_msg__pack_to_buffer
                     (const ActionGetPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetPerflowMsg *
       action_get_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetPerflowMsg *)
     protobuf_c_message_unpack (&action_get_perflow_msg__descriptor,
                                allocator, len, data);
}
void   action_get_perflow_msg__free_unpacked
                     (ActionGetPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_perflow_ack_msg__init
                     (ActionGetPerflowAckMsg         *message)
{
  static const ActionGetPerflowAckMsg init_value = ACTION_GET_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_get_perflow_ack_msg__get_packed_size
                     (const ActionGetPerflowAckMsg *message)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_perflow_ack_msg__pack
                     (const ActionGetPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_perflow_ack_msg__pack_to_buffer
                     (const ActionGetPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetPerflowAckMsg *
       action_get_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetPerflowAckMsg *)
     protobuf_c_message_unpack (&action_get_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_get_perflow_ack_msg__free_unpacked
                     (ActionGetPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_state__init
                     (ActionState         *message)
{
  static const ActionState init_value = ACTION_STATE__INIT;
  *message = init_value;
}
size_t action_state__get_packed_size
                     (const ActionState *message)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_state__pack
                     (const ActionState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_state__pack_to_buffer
                     (const ActionState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionState *
       action_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionState *)
     protobuf_c_message_unpack (&action_state__descriptor,
                                allocator, len, data);
}
void   action_state__free_unpacked
                     (ActionState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_perflow_msg__init
                     (ActionPutPerflowMsg         *message)
{
  static const ActionPutPerflowMsg init_value = ACTION_PUT_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_put_perflow_msg__get_packed_size
                     (const ActionPutPerflowMsg *message)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_perflow_msg__pack
                     (const ActionPutPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_perflow_msg__pack_to_buffer
                     (const ActionPutPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutPerflowMsg *
       action_put_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutPerflowMsg *)
     protobuf_c_message_unpack (&action_put_perflow_msg__descriptor,
                                allocator, len, data);
}
void   action_put_perflow_msg__free_unpacked
                     (ActionPutPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_perflow_ack_msg__init
                     (ActionPutPerflowAckMsg         *message)
{
  static const ActionPutPerflowAckMsg init_value = ACTION_PUT_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_put_perflow_ack_msg__get_packed_size
                     (const ActionPutPerflowAckMsg *message)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_perflow_ack_msg__pack
                     (const ActionPutPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_perflow_ack_msg__pack_to_buffer
                     (const ActionPutPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutPerflowAckMsg *
       action_put_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutPerflowAckMsg *)
     protobuf_c_message_unpack (&action_put_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_put_perflow_ack_msg__free_unpacked
                     (ActionPutPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue my_action_message__data_type__enum_values_by_number[6] =
{
  { "SynType", "MY_ACTION_MESSAGE__DATA_TYPE__SynType", 1 },
  { "ActionGetPerflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetPerflowMsgType", 2 },
  { "ActionGetPerflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionGetPerflowAckMsgType", 3 },
  { "ActionStateType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionStateType", 4 },
  { "ActionPutPerflowMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutPerflowMsgType", 5 },
  { "ActionPutPerflowAckMsgType", "MY_ACTION_MESSAGE__DATA_TYPE__ActionPutPerflowAckMsgType", 6 },
};
static const ProtobufCIntRange my_action_message__data_type__value_ranges[] = {
{1, 0},{0, 6}
};
static const ProtobufCEnumValueIndex my_action_message__data_type__enum_values_by_name[6] =
{
  { "ActionGetPerflowAckMsgType", 2 },
  { "ActionGetPerflowMsgType", 1 },
  { "ActionPutPerflowAckMsgType", 5 },
  { "ActionPutPerflowMsgType", 4 },
  { "ActionStateType", 3 },
  { "SynType", 0 },
};
const ProtobufCEnumDescriptor my_action_message__data_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MyActionMessage.DataType",
  "DataType",
  "MyActionMessage__DataType",
  "",
  6,
  my_action_message__data_type__enum_values_by_number,
  6,
  my_action_message__data_type__enum_values_by_name,
  1,
  my_action_message__data_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor my_action_message__field_descriptors[7] =
{
  {
    "data_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MyActionMessage, data_type),
    &my_action_message__data_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionsyn",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionsyn),
    &action_syn__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetPerflowMsg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetperflowmsg),
    &action_get_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetPerflowAckMsg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actiongetperflowackmsg),
    &action_get_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionState",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionstate),
    &action_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutPerflowMsg",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputperflowmsg),
    &action_put_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutPerflowAckMsg",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyActionMessage, message_case),
    offsetof(MyActionMessage, actionputperflowackmsg),
    &action_put_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned my_action_message__field_indices_by_name[] = {
  3,   /* field[3] = actionGetPerflowAckMsg */
  2,   /* field[2] = actionGetPerflowMsg */
  6,   /* field[6] = actionPutPerflowAckMsg */
  5,   /* field[5] = actionPutPerflowMsg */
  4,   /* field[4] = actionState */
  1,   /* field[1] = actionsyn */
  0,   /* field[0] = data_type */
};
static const ProtobufCIntRange my_action_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor my_action_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MyActionMessage",
  "MyActionMessage",
  "MyActionMessage",
  "",
  sizeof(MyActionMessage),
  7,
  my_action_message__field_descriptors,
  my_action_message__field_indices_by_name,
  1,  my_action_message__number_ranges,
  (ProtobufCMessageInit) my_action_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_syn__field_descriptors[2] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionSyn, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionSyn, has_pid),
    offsetof(ActionSyn, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_syn__field_indices_by_name[] = {
  0,   /* field[0] = host */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange action_syn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_syn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionSyn",
  "ActionSyn",
  "ActionSyn",
  "",
  sizeof(ActionSyn),
  2,
  action_syn__field_descriptors,
  action_syn__field_indices_by_name,
  1,  action_syn__number_ranges,
  (ProtobufCMessageInit) action_syn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_perflow_msg__field_descriptors[2] =
{
  {
    "hw_proto",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionGetPerflowMsg, has_hw_proto),
    offsetof(ActionGetPerflowMsg, hw_proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionGetPerflowMsg, has_proto),
    offsetof(ActionGetPerflowMsg, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = hw_proto */
  1,   /* field[1] = proto */
};
static const ProtobufCIntRange action_get_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_get_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetPerflowMsg",
  "ActionGetPerflowMsg",
  "ActionGetPerflowMsg",
  "",
  sizeof(ActionGetPerflowMsg),
  2,
  action_get_perflow_msg__field_descriptors,
  action_get_perflow_msg__field_indices_by_name,
  1,  action_get_perflow_msg__number_ranges,
  (ProtobufCMessageInit) action_get_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_perflow_ack_msg__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionGetPerflowAckMsg, has_count),
    offsetof(ActionGetPerflowAckMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_perflow_ack_msg__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange action_get_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_get_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetPerflowAckMsg",
  "ActionGetPerflowAckMsg",
  "ActionGetPerflowAckMsg",
  "",
  sizeof(ActionGetPerflowAckMsg),
  1,
  action_get_perflow_ack_msg__field_descriptors,
  action_get_perflow_ack_msg__field_indices_by_name,
  1,  action_get_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_get_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_state__field_descriptors[3] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionState, has_data),
    offsetof(ActionState, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_cxid),
    offsetof(ActionState, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionState, has_hash),
    offsetof(ActionState, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_state__field_indices_by_name[] = {
  1,   /* field[1] = cxid */
  0,   /* field[0] = data */
  2,   /* field[2] = hash */
};
static const ProtobufCIntRange action_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor action_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionState",
  "ActionState",
  "ActionState",
  "",
  sizeof(ActionState),
  3,
  action_state__field_descriptors,
  action_state__field_indices_by_name,
  1,  action_state__number_ranges,
  (ProtobufCMessageInit) action_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_perflow_msg__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionPutPerflowMsg, state),
    &action_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange action_put_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_put_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "",
  sizeof(ActionPutPerflowMsg),
  1,
  action_put_perflow_msg__field_descriptors,
  action_put_perflow_msg__field_indices_by_name,
  1,  action_put_perflow_msg__number_ranges,
  (ProtobufCMessageInit) action_put_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_perflow_ack_msg__field_descriptors[2] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionPutPerflowAckMsg, has_hash),
    offsetof(ActionPutPerflowAckMsg, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionPutPerflowAckMsg, has_cxid),
    offsetof(ActionPutPerflowAckMsg, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_perflow_ack_msg__field_indices_by_name[] = {
  1,   /* field[1] = cxid */
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange action_put_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_put_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutPerflowAckMsg",
  "ActionPutPerflowAckMsg",
  "ActionPutPerflowAckMsg",
  "",
  sizeof(ActionPutPerflowAckMsg),
  2,
  action_put_perflow_ack_msg__field_descriptors,
  action_put_perflow_ack_msg__field_indices_by_name,
  1,  action_put_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_put_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
