/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: myMessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "myMessage.pb-c.h"
void   my_message__init
                     (MyMessage         *message)
{
  static const MyMessage init_value = MY_MESSAGE__INIT;
  *message = init_value;
}
size_t my_message__get_packed_size
                     (const MyMessage *message)
{
  assert(message->base.descriptor == &my_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t my_message__pack
                     (const MyMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &my_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t my_message__pack_to_buffer
                     (const MyMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &my_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MyMessage *
       my_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MyMessage *)
     protobuf_c_message_unpack (&my_message__descriptor,
                                allocator, len, data);
}
void   my_message__free_unpacked
                     (MyMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &my_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   syn__init
                     (Syn         *message)
{
  static const Syn init_value = SYN__INIT;
  *message = init_value;
}
size_t syn__get_packed_size
                     (const Syn *message)
{
  assert(message->base.descriptor == &syn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t syn__pack
                     (const Syn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &syn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t syn__pack_to_buffer
                     (const Syn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &syn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Syn *
       syn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Syn *)
     protobuf_c_message_unpack (&syn__descriptor,
                                allocator, len, data);
}
void   syn__free_unpacked
                     (Syn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &syn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   person__init
                     (Person         *message)
{
  static const Person init_value = PERSON__INIT;
  *message = init_value;
}
size_t person__get_packed_size
                     (const Person *message)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t person__pack
                     (const Person *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t person__pack_to_buffer
                     (const Person *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Person *)
     protobuf_c_message_unpack (&person__descriptor,
                                allocator, len, data);
}
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &person__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conn_get_perflow_msg__init
                     (ConnGetPerflowMsg         *message)
{
  static const ConnGetPerflowMsg init_value = CONN_GET_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t conn_get_perflow_msg__get_packed_size
                     (const ConnGetPerflowMsg *message)
{
  assert(message->base.descriptor == &conn_get_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conn_get_perflow_msg__pack
                     (const ConnGetPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conn_get_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conn_get_perflow_msg__pack_to_buffer
                     (const ConnGetPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conn_get_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnGetPerflowMsg *
       conn_get_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnGetPerflowMsg *)
     protobuf_c_message_unpack (&conn_get_perflow_msg__descriptor,
                                allocator, len, data);
}
void   conn_get_perflow_msg__free_unpacked
                     (ConnGetPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conn_get_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conn_get_perflow_ack_msg__init
                     (ConnGetPerflowAckMsg         *message)
{
  static const ConnGetPerflowAckMsg init_value = CONN_GET_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t conn_get_perflow_ack_msg__get_packed_size
                     (const ConnGetPerflowAckMsg *message)
{
  assert(message->base.descriptor == &conn_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conn_get_perflow_ack_msg__pack
                     (const ConnGetPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conn_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conn_get_perflow_ack_msg__pack_to_buffer
                     (const ConnGetPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conn_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnGetPerflowAckMsg *
       conn_get_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnGetPerflowAckMsg *)
     protobuf_c_message_unpack (&conn_get_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   conn_get_perflow_ack_msg__free_unpacked
                     (ConnGetPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conn_get_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conn_state__init
                     (ConnState         *message)
{
  static const ConnState init_value = CONN_STATE__INIT;
  *message = init_value;
}
size_t conn_state__get_packed_size
                     (const ConnState *message)
{
  assert(message->base.descriptor == &conn_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conn_state__pack
                     (const ConnState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conn_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conn_state__pack_to_buffer
                     (const ConnState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conn_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnState *
       conn_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnState *)
     protobuf_c_message_unpack (&conn_state__descriptor,
                                allocator, len, data);
}
void   conn_state__free_unpacked
                     (ConnState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conn_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conn_put_perflow_msg__init
                     (ConnPutPerflowMsg         *message)
{
  static const ConnPutPerflowMsg init_value = CONN_PUT_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t conn_put_perflow_msg__get_packed_size
                     (const ConnPutPerflowMsg *message)
{
  assert(message->base.descriptor == &conn_put_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conn_put_perflow_msg__pack
                     (const ConnPutPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conn_put_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conn_put_perflow_msg__pack_to_buffer
                     (const ConnPutPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conn_put_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnPutPerflowMsg *
       conn_put_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnPutPerflowMsg *)
     protobuf_c_message_unpack (&conn_put_perflow_msg__descriptor,
                                allocator, len, data);
}
void   conn_put_perflow_msg__free_unpacked
                     (ConnPutPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conn_put_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conn_put_perflow_ack_msg__init
                     (ConnPutPerflowAckMsg         *message)
{
  static const ConnPutPerflowAckMsg init_value = CONN_PUT_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t conn_put_perflow_ack_msg__get_packed_size
                     (const ConnPutPerflowAckMsg *message)
{
  assert(message->base.descriptor == &conn_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conn_put_perflow_ack_msg__pack
                     (const ConnPutPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conn_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conn_put_perflow_ack_msg__pack_to_buffer
                     (const ConnPutPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conn_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnPutPerflowAckMsg *
       conn_put_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnPutPerflowAckMsg *)
     protobuf_c_message_unpack (&conn_put_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   conn_put_perflow_ack_msg__free_unpacked
                     (ConnPutPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conn_put_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_perflow_msg__init
                     (ActionGetPerflowMsg         *message)
{
  static const ActionGetPerflowMsg init_value = ACTION_GET_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_get_perflow_msg__get_packed_size
                     (const ActionGetPerflowMsg *message)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_perflow_msg__pack
                     (const ActionGetPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_perflow_msg__pack_to_buffer
                     (const ActionGetPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetPerflowMsg *
       action_get_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetPerflowMsg *)
     protobuf_c_message_unpack (&action_get_perflow_msg__descriptor,
                                allocator, len, data);
}
void   action_get_perflow_msg__free_unpacked
                     (ActionGetPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_get_perflow_ack_msg__init
                     (ActionGetPerflowAckMsg         *message)
{
  static const ActionGetPerflowAckMsg init_value = ACTION_GET_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_get_perflow_ack_msg__get_packed_size
                     (const ActionGetPerflowAckMsg *message)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_get_perflow_ack_msg__pack
                     (const ActionGetPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_get_perflow_ack_msg__pack_to_buffer
                     (const ActionGetPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionGetPerflowAckMsg *
       action_get_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionGetPerflowAckMsg *)
     protobuf_c_message_unpack (&action_get_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_get_perflow_ack_msg__free_unpacked
                     (ActionGetPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_get_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_state__init
                     (ActionState         *message)
{
  static const ActionState init_value = ACTION_STATE__INIT;
  *message = init_value;
}
size_t action_state__get_packed_size
                     (const ActionState *message)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_state__pack
                     (const ActionState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_state__pack_to_buffer
                     (const ActionState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionState *
       action_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionState *)
     protobuf_c_message_unpack (&action_state__descriptor,
                                allocator, len, data);
}
void   action_state__free_unpacked
                     (ActionState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_perflow_msg__init
                     (ActionPutPerflowMsg         *message)
{
  static const ActionPutPerflowMsg init_value = ACTION_PUT_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_put_perflow_msg__get_packed_size
                     (const ActionPutPerflowMsg *message)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_perflow_msg__pack
                     (const ActionPutPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_perflow_msg__pack_to_buffer
                     (const ActionPutPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutPerflowMsg *
       action_put_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutPerflowMsg *)
     protobuf_c_message_unpack (&action_put_perflow_msg__descriptor,
                                allocator, len, data);
}
void   action_put_perflow_msg__free_unpacked
                     (ActionPutPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_put_perflow_ack_msg__init
                     (ActionPutPerflowAckMsg         *message)
{
  static const ActionPutPerflowAckMsg init_value = ACTION_PUT_PERFLOW_ACK_MSG__INIT;
  *message = init_value;
}
size_t action_put_perflow_ack_msg__get_packed_size
                     (const ActionPutPerflowAckMsg *message)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_perflow_ack_msg__pack
                     (const ActionPutPerflowAckMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_perflow_ack_msg__pack_to_buffer
                     (const ActionPutPerflowAckMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutPerflowAckMsg *
       action_put_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutPerflowAckMsg *)
     protobuf_c_message_unpack (&action_put_perflow_ack_msg__descriptor,
                                allocator, len, data);
}
void   action_put_perflow_ack_msg__free_unpacked
                     (ActionPutPerflowAckMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_perflow_ack_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue my_message__data_type__enum_values_by_number[12] =
{
  { "SynType", "MY_MESSAGE__DATA_TYPE__SynType", 1 },
  { "PersonType", "MY_MESSAGE__DATA_TYPE__PersonType", 2 },
  { "ConnGetPerflowMsgType", "MY_MESSAGE__DATA_TYPE__ConnGetPerflowMsgType", 3 },
  { "ConnGetPerflowAckMsgType", "MY_MESSAGE__DATA_TYPE__ConnGetPerflowAckMsgType", 4 },
  { "ConnStateType", "MY_MESSAGE__DATA_TYPE__ConnStateType", 5 },
  { "ConnPutPerflowMsgType", "MY_MESSAGE__DATA_TYPE__ConnPutPerflowMsgType", 6 },
  { "ConnPutPerflowAckMsgType", "MY_MESSAGE__DATA_TYPE__ConnPutPerflowAckMsgType", 7 },
  { "ActionGetPerflowMsgType", "MY_MESSAGE__DATA_TYPE__ActionGetPerflowMsgType", 8 },
  { "ActionGetPerflowAckMsgType", "MY_MESSAGE__DATA_TYPE__ActionGetPerflowAckMsgType", 9 },
  { "ActionStateType", "MY_MESSAGE__DATA_TYPE__ActionStateType", 10 },
  { "ActionPutPerflowMsgType", "MY_MESSAGE__DATA_TYPE__ActionPutPerflowMsgType", 11 },
  { "ActionPutPerflowAckMsgType", "MY_MESSAGE__DATA_TYPE__ActionPutPerflowAckMsgType", 12 },
};
static const ProtobufCIntRange my_message__data_type__value_ranges[] = {
{1, 0},{0, 12}
};
static const ProtobufCEnumValueIndex my_message__data_type__enum_values_by_name[12] =
{
  { "ActionGetPerflowAckMsgType", 8 },
  { "ActionGetPerflowMsgType", 7 },
  { "ActionPutPerflowAckMsgType", 11 },
  { "ActionPutPerflowMsgType", 10 },
  { "ActionStateType", 9 },
  { "ConnGetPerflowAckMsgType", 3 },
  { "ConnGetPerflowMsgType", 2 },
  { "ConnPutPerflowAckMsgType", 6 },
  { "ConnPutPerflowMsgType", 5 },
  { "ConnStateType", 4 },
  { "PersonType", 1 },
  { "SynType", 0 },
};
const ProtobufCEnumDescriptor my_message__data_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MyMessage.DataType",
  "DataType",
  "MyMessage__DataType",
  "",
  12,
  my_message__data_type__enum_values_by_number,
  12,
  my_message__data_type__enum_values_by_name,
  1,
  my_message__data_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor my_message__field_descriptors[13] =
{
  {
    "data_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MyMessage, data_type),
    &my_message__data_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "syn",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, syn),
    &syn__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "person",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, person),
    &person__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connGetPerflowMsg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, conngetperflowmsg),
    &conn_get_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connGetPerflowAckMsg",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, conngetperflowackmsg),
    &conn_get_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connState",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, connstate),
    &conn_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connPutPerflowMsg",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, connputperflowmsg),
    &conn_put_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connPutPerflowAckMsg",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, connputperflowackmsg),
    &conn_put_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetPerflowMsg",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, actiongetperflowmsg),
    &action_get_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionGetPerflowAckMsg",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, actiongetperflowackmsg),
    &action_get_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionState",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, actionstate),
    &action_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutPerflowMsg",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, actionputperflowmsg),
    &action_put_perflow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionPutPerflowAckMsg",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MyMessage, message_case),
    offsetof(MyMessage, actionputperflowackmsg),
    &action_put_perflow_ack_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned my_message__field_indices_by_name[] = {
  9,   /* field[9] = actionGetPerflowAckMsg */
  8,   /* field[8] = actionGetPerflowMsg */
  12,   /* field[12] = actionPutPerflowAckMsg */
  11,   /* field[11] = actionPutPerflowMsg */
  10,   /* field[10] = actionState */
  4,   /* field[4] = connGetPerflowAckMsg */
  3,   /* field[3] = connGetPerflowMsg */
  7,   /* field[7] = connPutPerflowAckMsg */
  6,   /* field[6] = connPutPerflowMsg */
  5,   /* field[5] = connState */
  0,   /* field[0] = data_type */
  2,   /* field[2] = person */
  1,   /* field[1] = syn */
};
static const ProtobufCIntRange my_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor my_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MyMessage",
  "MyMessage",
  "MyMessage",
  "",
  sizeof(MyMessage),
  13,
  my_message__field_descriptors,
  my_message__field_indices_by_name,
  1,  my_message__number_ranges,
  (ProtobufCMessageInit) my_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor syn__field_descriptors[2] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Syn, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Syn, has_pid),
    offsetof(Syn, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned syn__field_indices_by_name[] = {
  0,   /* field[0] = host */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange syn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor syn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Syn",
  "Syn",
  "Syn",
  "",
  sizeof(Syn),
  2,
  syn__field_descriptors,
  syn__field_indices_by_name,
  1,  syn__number_ranges,
  (ProtobufCMessageInit) syn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor person__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "age",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Person, has_age),
    offsetof(Person, age),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned person__field_indices_by_name[] = {
  2,   /* field[2] = address */
  1,   /* field[1] = age */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange person__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor person__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Person",
  "Person",
  "Person",
  "",
  sizeof(Person),
  3,
  person__field_descriptors,
  person__field_indices_by_name,
  1,  person__number_ranges,
  (ProtobufCMessageInit) person__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conn_get_perflow_msg__field_descriptors[1] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ConnGetPerflowMsg, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conn_get_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = key */
};
static const ProtobufCIntRange conn_get_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor conn_get_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnGetPerflowMsg",
  "ConnGetPerflowMsg",
  "ConnGetPerflowMsg",
  "",
  sizeof(ConnGetPerflowMsg),
  1,
  conn_get_perflow_msg__field_descriptors,
  conn_get_perflow_msg__field_indices_by_name,
  1,  conn_get_perflow_msg__number_ranges,
  (ProtobufCMessageInit) conn_get_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conn_get_perflow_ack_msg__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ConnGetPerflowAckMsg, has_count),
    offsetof(ConnGetPerflowAckMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conn_get_perflow_ack_msg__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange conn_get_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor conn_get_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnGetPerflowAckMsg",
  "ConnGetPerflowAckMsg",
  "ConnGetPerflowAckMsg",
  "",
  sizeof(ConnGetPerflowAckMsg),
  1,
  conn_get_perflow_ack_msg__field_descriptors,
  conn_get_perflow_ack_msg__field_indices_by_name,
  1,  conn_get_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) conn_get_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conn_state__field_descriptors[3] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ConnState, has_data),
    offsetof(ConnState, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ConnState, has_cxid),
    offsetof(ConnState, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ConnState, has_hash),
    offsetof(ConnState, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conn_state__field_indices_by_name[] = {
  1,   /* field[1] = cxid */
  0,   /* field[0] = data */
  2,   /* field[2] = hash */
};
static const ProtobufCIntRange conn_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor conn_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnState",
  "ConnState",
  "ConnState",
  "",
  sizeof(ConnState),
  3,
  conn_state__field_descriptors,
  conn_state__field_indices_by_name,
  1,  conn_state__number_ranges,
  (ProtobufCMessageInit) conn_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conn_put_perflow_msg__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ConnPutPerflowMsg, state),
    &conn_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conn_put_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange conn_put_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor conn_put_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnPutPerflowMsg",
  "ConnPutPerflowMsg",
  "ConnPutPerflowMsg",
  "",
  sizeof(ConnPutPerflowMsg),
  1,
  conn_put_perflow_msg__field_descriptors,
  conn_put_perflow_msg__field_indices_by_name,
  1,  conn_put_perflow_msg__number_ranges,
  (ProtobufCMessageInit) conn_put_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conn_put_perflow_ack_msg__field_descriptors[2] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ConnPutPerflowAckMsg, has_hash),
    offsetof(ConnPutPerflowAckMsg, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ConnPutPerflowAckMsg, has_cxid),
    offsetof(ConnPutPerflowAckMsg, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conn_put_perflow_ack_msg__field_indices_by_name[] = {
  1,   /* field[1] = cxid */
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange conn_put_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor conn_put_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnPutPerflowAckMsg",
  "ConnPutPerflowAckMsg",
  "ConnPutPerflowAckMsg",
  "",
  sizeof(ConnPutPerflowAckMsg),
  2,
  conn_put_perflow_ack_msg__field_descriptors,
  conn_put_perflow_ack_msg__field_indices_by_name,
  1,  conn_put_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) conn_put_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_perflow_msg__field_descriptors[1] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionGetPerflowMsg, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = key */
};
static const ProtobufCIntRange action_get_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_get_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetPerflowMsg",
  "ActionGetPerflowMsg",
  "ActionGetPerflowMsg",
  "",
  sizeof(ActionGetPerflowMsg),
  1,
  action_get_perflow_msg__field_descriptors,
  action_get_perflow_msg__field_indices_by_name,
  1,  action_get_perflow_msg__number_ranges,
  (ProtobufCMessageInit) action_get_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_get_perflow_ack_msg__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionGetPerflowAckMsg, has_count),
    offsetof(ActionGetPerflowAckMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_get_perflow_ack_msg__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange action_get_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_get_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionGetPerflowAckMsg",
  "ActionGetPerflowAckMsg",
  "ActionGetPerflowAckMsg",
  "",
  sizeof(ActionGetPerflowAckMsg),
  1,
  action_get_perflow_ack_msg__field_descriptors,
  action_get_perflow_ack_msg__field_indices_by_name,
  1,  action_get_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_get_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_state__field_descriptors[3] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionState, has_data),
    offsetof(ActionState, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(ActionState, has_cxid),
    offsetof(ActionState, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ActionState, has_hash),
    offsetof(ActionState, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_state__field_indices_by_name[] = {
  1,   /* field[1] = cxid */
  0,   /* field[0] = data */
  2,   /* field[2] = hash */
};
static const ProtobufCIntRange action_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor action_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionState",
  "ActionState",
  "ActionState",
  "",
  sizeof(ActionState),
  3,
  action_state__field_descriptors,
  action_state__field_indices_by_name,
  1,  action_state__number_ranges,
  (ProtobufCMessageInit) action_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_perflow_msg__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionPutPerflowMsg, state),
    &action_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange action_put_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_put_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "",
  sizeof(ActionPutPerflowMsg),
  1,
  action_put_perflow_msg__field_descriptors,
  action_put_perflow_msg__field_indices_by_name,
  1,  action_put_perflow_msg__number_ranges,
  (ProtobufCMessageInit) action_put_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_put_perflow_ack_msg__field_descriptors[2] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionPutPerflowAckMsg, has_hash),
    offsetof(ActionPutPerflowAckMsg, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cxid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(ActionPutPerflowAckMsg, has_cxid),
    offsetof(ActionPutPerflowAckMsg, cxid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_perflow_ack_msg__field_indices_by_name[] = {
  1,   /* field[1] = cxid */
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange action_put_perflow_ack_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_put_perflow_ack_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutPerflowAckMsg",
  "ActionPutPerflowAckMsg",
  "ActionPutPerflowAckMsg",
  "",
  sizeof(ActionPutPerflowAckMsg),
  2,
  action_put_perflow_ack_msg__field_descriptors,
  action_put_perflow_ack_msg__field_indices_by_name,
  1,  action_put_perflow_ack_msg__number_ranges,
  (ProtobufCMessageInit) action_put_perflow_ack_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
