/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: putPerflow.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "putPerflow.pb-c.h"
void   put_perflow_msg__init
                     (PutPerflowMsg         *message)
{
  static const PutPerflowMsg init_value = PUT_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t put_perflow_msg__get_packed_size
                     (const PutPerflowMsg *message)
{
  assert(message->base.descriptor == &put_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t put_perflow_msg__pack
                     (const PutPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &put_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t put_perflow_msg__pack_to_buffer
                     (const PutPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &put_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PutPerflowMsg *
       put_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PutPerflowMsg *)
     protobuf_c_message_unpack (&put_perflow_msg__descriptor,
                                allocator, len, data);
}
void   put_perflow_msg__free_unpacked
                     (PutPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &put_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor put_perflow_msg__field_descriptors[2] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(PutPerflowMsg, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(PutPerflowMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned put_perflow_msg__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = data */
};
static const ProtobufCIntRange put_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor put_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PutPerflowMsg",
  "PutPerflowMsg",
  "PutPerflowMsg",
  "",
  sizeof(PutPerflowMsg),
  2,
  put_perflow_msg__field_descriptors,
  put_perflow_msg__field_indices_by_name,
  1,  put_perflow_msg__number_ranges,
  (ProtobufCMessageInit) put_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
