/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: flowstate.proto */

#ifndef PROTOBUF_C_flowstate_2eproto__INCLUDED
#define PROTOBUF_C_flowstate_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _FlowState FlowState;


/* --- enums --- */


/* --- messages --- */

struct  _FlowState
{
  ProtobufCMessage base;
  int32_t data;
};
#define FLOW_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&flow_state__descriptor) \
    , 0 }


/* FlowState methods */
void   flow_state__init
                     (FlowState         *message);
size_t flow_state__get_packed_size
                     (const FlowState   *message);
size_t flow_state__pack
                     (const FlowState   *message,
                      uint8_t             *out);
size_t flow_state__pack_to_buffer
                     (const FlowState   *message,
                      ProtobufCBuffer     *buffer);
FlowState *
       flow_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   flow_state__free_unpacked
                     (FlowState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FlowState_Closure)
                 (const FlowState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor flow_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_flowstate_2eproto__INCLUDED */
