/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: information.proto */

#ifndef PROTOBUF_C_information_2eproto__INCLUDED
#define PROTOBUF_C_information_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Information Information;


/* --- enums --- */


/* --- messages --- */

struct  _Information
{
  ProtobufCMessage base;
  uint32_t personnum;
  char *content;
};
#define INFORMATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&information__descriptor) \
    , 0, NULL }


/* Information methods */
void   information__init
                     (Information         *message);
size_t information__get_packed_size
                     (const Information   *message);
size_t information__pack
                     (const Information   *message,
                      uint8_t             *out);
size_t information__pack_to_buffer
                     (const Information   *message,
                      ProtobufCBuffer     *buffer);
Information *
       information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   information__free_unpacked
                     (Information *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Information_Closure)
                 (const Information *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor information__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_information_2eproto__INCLUDED */
