/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: actionPutPerflowMsg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "actionPutPerflowMsg.pb-c.h"
void   action_put_perflow_msg__init
                     (ActionPutPerflowMsg         *message)
{
  static const ActionPutPerflowMsg init_value = ACTION_PUT_PERFLOW_MSG__INIT;
  *message = init_value;
}
size_t action_put_perflow_msg__get_packed_size
                     (const ActionPutPerflowMsg *message)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_put_perflow_msg__pack
                     (const ActionPutPerflowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_put_perflow_msg__pack_to_buffer
                     (const ActionPutPerflowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionPutPerflowMsg *
       action_put_perflow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionPutPerflowMsg *)
     protobuf_c_message_unpack (&action_put_perflow_msg__descriptor,
                                allocator, len, data);
}
void   action_put_perflow_msg__free_unpacked
                     (ActionPutPerflowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_put_perflow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor action_put_perflow_msg__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActionPutPerflowMsg, state),
    &action_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_put_perflow_msg__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange action_put_perflow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_put_perflow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "ActionPutPerflowMsg",
  "",
  sizeof(ActionPutPerflowMsg),
  1,
  action_put_perflow_msg__field_descriptors,
  action_put_perflow_msg__field_indices_by_name,
  1,  action_put_perflow_msg__number_ranges,
  (ProtobufCMessageInit) action_put_perflow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
