/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: putPerflowAckMsg.proto */

#ifndef PROTOBUF_C_putPerflowAckMsg_2eproto__INCLUDED
#define PROTOBUF_C_putPerflowAckMsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _PutPerflowAckMsg PutPerflowAckMsg;


/* --- enums --- */


/* --- messages --- */

struct  _PutPerflowAckMsg
{
  ProtobufCMessage base;
  uint32_t count;
};
#define PUT_PERFLOW_ACK_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&put_perflow_ack_msg__descriptor) \
    , 0 }


/* PutPerflowAckMsg methods */
void   put_perflow_ack_msg__init
                     (PutPerflowAckMsg         *message);
size_t put_perflow_ack_msg__get_packed_size
                     (const PutPerflowAckMsg   *message);
size_t put_perflow_ack_msg__pack
                     (const PutPerflowAckMsg   *message,
                      uint8_t             *out);
size_t put_perflow_ack_msg__pack_to_buffer
                     (const PutPerflowAckMsg   *message,
                      ProtobufCBuffer     *buffer);
PutPerflowAckMsg *
       put_perflow_ack_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   put_perflow_ack_msg__free_unpacked
                     (PutPerflowAckMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PutPerflowAckMsg_Closure)
                 (const PutPerflowAckMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor put_perflow_ack_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_putPerflowAckMsg_2eproto__INCLUDED */
